/*
 * This file is generated by jOOQ.
 */
package org.vaccineimpact.orderlyweb.db.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.vaccineimpact.orderlyweb.db.tables.FileArtefact;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FileArtefactRecord extends UpdatableRecordImpl<FileArtefactRecord> implements Record4<Integer, Integer, String, String> {

    private static final long serialVersionUID = -2061161465;

    /**
     * Setter for <code>file_artefact.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>file_artefact.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>file_artefact.artefact</code>.
     */
    public void setArtefact(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>file_artefact.artefact</code>.
     */
    public Integer getArtefact() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>file_artefact.file_hash</code>.
     */
    public void setFileHash(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>file_artefact.file_hash</code>.
     */
    public String getFileHash() {
        return (String) get(2);
    }

    /**
     * Setter for <code>file_artefact.filename</code>.
     */
    public void setFilename(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>file_artefact.filename</code>.
     */
    public String getFilename() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, Integer, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return FileArtefact.FILE_ARTEFACT.ID;
    }

    @Override
    public Field<Integer> field2() {
        return FileArtefact.FILE_ARTEFACT.ARTEFACT;
    }

    @Override
    public Field<String> field3() {
        return FileArtefact.FILE_ARTEFACT.FILE_HASH;
    }

    @Override
    public Field<String> field4() {
        return FileArtefact.FILE_ARTEFACT.FILENAME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getArtefact();
    }

    @Override
    public String component3() {
        return getFileHash();
    }

    @Override
    public String component4() {
        return getFilename();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getArtefact();
    }

    @Override
    public String value3() {
        return getFileHash();
    }

    @Override
    public String value4() {
        return getFilename();
    }

    @Override
    public FileArtefactRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public FileArtefactRecord value2(Integer value) {
        setArtefact(value);
        return this;
    }

    @Override
    public FileArtefactRecord value3(String value) {
        setFileHash(value);
        return this;
    }

    @Override
    public FileArtefactRecord value4(String value) {
        setFilename(value);
        return this;
    }

    @Override
    public FileArtefactRecord values(Integer value1, Integer value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FileArtefactRecord
     */
    public FileArtefactRecord() {
        super(FileArtefact.FILE_ARTEFACT);
    }

    /**
     * Create a detached, initialised FileArtefactRecord
     */
    public FileArtefactRecord(Integer id, Integer artefact, String fileHash, String filename) {
        super(FileArtefact.FILE_ARTEFACT);

        set(0, id);
        set(1, artefact);
        set(2, fileHash);
        set(3, filename);
    }
}
