/*
 * This file is generated by jOOQ.
 */
package org.vaccineimpact.orderlyweb.db.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.TableRecordImpl;
import org.vaccineimpact.orderlyweb.db.tables.OrderlywebSettings;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderlywebSettingsRecord extends TableRecordImpl<OrderlywebSettingsRecord> implements Record1<Boolean> {

    private static final long serialVersionUID = 1252462502;

    /**
     * Setter for <code>orderlyweb_settings.auth_allow_guest</code>.
     */
    public void setAuthAllowGuest(Boolean value) {
        set(0, value);
    }

    /**
     * Getter for <code>orderlyweb_settings.auth_allow_guest</code>.
     */
    public Boolean getAuthAllowGuest() {
        return (Boolean) get(0);
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row1<Boolean> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    @Override
    public Row1<Boolean> valuesRow() {
        return (Row1) super.valuesRow();
    }

    @Override
    public Field<Boolean> field1() {
        return OrderlywebSettings.ORDERLYWEB_SETTINGS.AUTH_ALLOW_GUEST;
    }

    @Override
    public Boolean component1() {
        return getAuthAllowGuest();
    }

    @Override
    public Boolean value1() {
        return getAuthAllowGuest();
    }

    @Override
    public OrderlywebSettingsRecord value1(Boolean value) {
        setAuthAllowGuest(value);
        return this;
    }

    @Override
    public OrderlywebSettingsRecord values(Boolean value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderlywebSettingsRecord
     */
    public OrderlywebSettingsRecord() {
        super(OrderlywebSettings.ORDERLYWEB_SETTINGS);
    }

    /**
     * Create a detached, initialised OrderlywebSettingsRecord
     */
    public OrderlywebSettingsRecord(Boolean authAllowGuest) {
        super(OrderlywebSettings.ORDERLYWEB_SETTINGS);

        set(0, authAllowGuest);
    }
}
