/*
 * This file is generated by jOOQ.
 */
package org.vaccineimpact.orderlyweb.db.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.vaccineimpact.orderlyweb.db.tables.OrderlywebUserGroupPermission;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderlywebUserGroupPermissionRecord extends UpdatableRecordImpl<OrderlywebUserGroupPermissionRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = -4832451;

    /**
     * Setter for <code>orderlyweb_user_group_permission.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>orderlyweb_user_group_permission.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>orderlyweb_user_group_permission.user_group</code>.
     */
    public void setUserGroup(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>orderlyweb_user_group_permission.user_group</code>.
     */
    public String getUserGroup() {
        return (String) get(1);
    }

    /**
     * Setter for <code>orderlyweb_user_group_permission.permission</code>.
     */
    public void setPermission(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>orderlyweb_user_group_permission.permission</code>.
     */
    public String getPermission() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return OrderlywebUserGroupPermission.ORDERLYWEB_USER_GROUP_PERMISSION.ID;
    }

    @Override
    public Field<String> field2() {
        return OrderlywebUserGroupPermission.ORDERLYWEB_USER_GROUP_PERMISSION.USER_GROUP;
    }

    @Override
    public Field<String> field3() {
        return OrderlywebUserGroupPermission.ORDERLYWEB_USER_GROUP_PERMISSION.PERMISSION;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUserGroup();
    }

    @Override
    public String component3() {
        return getPermission();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUserGroup();
    }

    @Override
    public String value3() {
        return getPermission();
    }

    @Override
    public OrderlywebUserGroupPermissionRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public OrderlywebUserGroupPermissionRecord value2(String value) {
        setUserGroup(value);
        return this;
    }

    @Override
    public OrderlywebUserGroupPermissionRecord value3(String value) {
        setPermission(value);
        return this;
    }

    @Override
    public OrderlywebUserGroupPermissionRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderlywebUserGroupPermissionRecord
     */
    public OrderlywebUserGroupPermissionRecord() {
        super(OrderlywebUserGroupPermission.ORDERLYWEB_USER_GROUP_PERMISSION);
    }

    /**
     * Create a detached, initialised OrderlywebUserGroupPermissionRecord
     */
    public OrderlywebUserGroupPermissionRecord(Integer id, String userGroup, String permission) {
        super(OrderlywebUserGroupPermission.ORDERLYWEB_USER_GROUP_PERMISSION);

        set(0, id);
        set(1, userGroup);
        set(2, permission);
    }
}
