/*
 * This file is generated by jOOQ.
 */
package org.vaccineimpact.orderlyweb.db.tables.records;


import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;
import org.vaccineimpact.orderlyweb.db.tables.OrderlywebUserGroupPermissionAll;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderlywebUserGroupPermissionAllRecord extends TableRecordImpl<OrderlywebUserGroupPermissionAllRecord> implements Record5<Integer, String, String, Object, String> {

    private static final long serialVersionUID = 1346742955;

    /**
     * Setter for <code>orderlyweb_user_group_permission_all.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>orderlyweb_user_group_permission_all.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>orderlyweb_user_group_permission_all.user_group</code>.
     */
    public void setUserGroup(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>orderlyweb_user_group_permission_all.user_group</code>.
     */
    public String getUserGroup() {
        return (String) get(1);
    }

    /**
     * Setter for <code>orderlyweb_user_group_permission_all.permission</code>.
     */
    public void setPermission(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>orderlyweb_user_group_permission_all.permission</code>.
     */
    public String getPermission() {
        return (String) get(2);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public void setScopePrefix(Object value) {
        set(3, value);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public Object getScopePrefix() {
        return get(3);
    }

    /**
     * Setter for <code>orderlyweb_user_group_permission_all.scope_id</code>.
     */
    public void setScopeId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>orderlyweb_user_group_permission_all.scope_id</code>.
     */
    public String getScopeId() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, Object, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, String, Object, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return OrderlywebUserGroupPermissionAll.ORDERLYWEB_USER_GROUP_PERMISSION_ALL.ID;
    }

    @Override
    public Field<String> field2() {
        return OrderlywebUserGroupPermissionAll.ORDERLYWEB_USER_GROUP_PERMISSION_ALL.USER_GROUP;
    }

    @Override
    public Field<String> field3() {
        return OrderlywebUserGroupPermissionAll.ORDERLYWEB_USER_GROUP_PERMISSION_ALL.PERMISSION;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    @Override
    public Field<Object> field4() {
        return OrderlywebUserGroupPermissionAll.ORDERLYWEB_USER_GROUP_PERMISSION_ALL.SCOPE_PREFIX;
    }

    @Override
    public Field<String> field5() {
        return OrderlywebUserGroupPermissionAll.ORDERLYWEB_USER_GROUP_PERMISSION_ALL.SCOPE_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUserGroup();
    }

    @Override
    public String component3() {
        return getPermission();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    @Override
    public Object component4() {
        return getScopePrefix();
    }

    @Override
    public String component5() {
        return getScopeId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUserGroup();
    }

    @Override
    public String value3() {
        return getPermission();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    @Override
    public Object value4() {
        return getScopePrefix();
    }

    @Override
    public String value5() {
        return getScopeId();
    }

    @Override
    public OrderlywebUserGroupPermissionAllRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public OrderlywebUserGroupPermissionAllRecord value2(String value) {
        setUserGroup(value);
        return this;
    }

    @Override
    public OrderlywebUserGroupPermissionAllRecord value3(String value) {
        setPermission(value);
        return this;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    @Override
    public OrderlywebUserGroupPermissionAllRecord value4(Object value) {
        setScopePrefix(value);
        return this;
    }

    @Override
    public OrderlywebUserGroupPermissionAllRecord value5(String value) {
        setScopeId(value);
        return this;
    }

    @Override
    public OrderlywebUserGroupPermissionAllRecord values(Integer value1, String value2, String value3, Object value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderlywebUserGroupPermissionAllRecord
     */
    public OrderlywebUserGroupPermissionAllRecord() {
        super(OrderlywebUserGroupPermissionAll.ORDERLYWEB_USER_GROUP_PERMISSION_ALL);
    }

    /**
     * Create a detached, initialised OrderlywebUserGroupPermissionAllRecord
     */
    public OrderlywebUserGroupPermissionAllRecord(Integer id, String userGroup, String permission, Object scopePrefix, String scopeId) {
        super(OrderlywebUserGroupPermissionAll.ORDERLYWEB_USER_GROUP_PERMISSION_ALL);

        set(0, id);
        set(1, userGroup);
        set(2, permission);
        set(3, scopePrefix);
        set(4, scopeId);
    }
}
