/*
 * This file is generated by jOOQ.
*/
package org.vaccineimpact.orderlyweb.db.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;
import org.vaccineimpact.orderlyweb.db.tables.OrderlywebReportTag;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderlywebReportTagRecord extends UpdatableRecordImpl<OrderlywebReportTagRecord> implements Record2<String, String> {

    private static final long serialVersionUID = 479248758;

    /**
     * Setter for <code>orderlyweb_report_tag.report</code>.
     */
    public void setReport(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>orderlyweb_report_tag.report</code>.
     */
    public String getReport() {
        return (String) get(0);
    }

    /**
     * Setter for <code>orderlyweb_report_tag.tag</code>.
     */
    public void setTag(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>orderlyweb_report_tag.tag</code>.
     */
    public String getTag() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return OrderlywebReportTag.ORDERLYWEB_REPORT_TAG.REPORT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return OrderlywebReportTag.ORDERLYWEB_REPORT_TAG.TAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getReport();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderlywebReportTagRecord value1(String value) {
        setReport(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderlywebReportTagRecord value2(String value) {
        setTag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderlywebReportTagRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderlywebReportTagRecord
     */
    public OrderlywebReportTagRecord() {
        super(OrderlywebReportTag.ORDERLYWEB_REPORT_TAG);
    }

    /**
     * Create a detached, initialised OrderlywebReportTagRecord
     */
    public OrderlywebReportTagRecord(String report, String tag) {
        super(OrderlywebReportTag.ORDERLYWEB_REPORT_TAG);

        set(0, report);
        set(1, tag);
    }
}
