/*
 * This file is generated by jOOQ.
*/
package org.vaccineimpact.orderlyweb.db.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;
import org.vaccineimpact.orderlyweb.db.tables.OrderlywebDocument;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderlywebDocumentRecord extends UpdatableRecordImpl<OrderlywebDocumentRecord> implements Record8<String, String, Integer, String, String, String, Integer, Integer> {

    private static final long serialVersionUID = -1350740571;

    /**
     * Setter for <code>orderlyweb_document.path</code>.
     */
    public void setPath(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>orderlyweb_document.path</code>.
     */
    public String getPath() {
        return (String) get(0);
    }

    /**
     * Setter for <code>orderlyweb_document.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>orderlyweb_document.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>orderlyweb_document.show</code>.
     */
    public void setShow(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>orderlyweb_document.show</code>.
     */
    public Integer getShow() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>orderlyweb_document.display_name</code>.
     */
    public void setDisplayName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>orderlyweb_document.display_name</code>.
     */
    public String getDisplayName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>orderlyweb_document.description</code>.
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>orderlyweb_document.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>orderlyweb_document.parent</code>.
     */
    public void setParent(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>orderlyweb_document.parent</code>.
     */
    public String getParent() {
        return (String) get(5);
    }

    /**
     * Setter for <code>orderlyweb_document.is_file</code>.
     */
    public void setIsFile(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>orderlyweb_document.is_file</code>.
     */
    public Integer getIsFile() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>orderlyweb_document.external</code>.
     */
    public void setExternal(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>orderlyweb_document.external</code>.
     */
    public Integer getExternal() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, String, Integer, String, String, String, Integer, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, String, Integer, String, String, String, Integer, Integer> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return OrderlywebDocument.ORDERLYWEB_DOCUMENT.PATH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return OrderlywebDocument.ORDERLYWEB_DOCUMENT.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return OrderlywebDocument.ORDERLYWEB_DOCUMENT.SHOW;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return OrderlywebDocument.ORDERLYWEB_DOCUMENT.DISPLAY_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return OrderlywebDocument.ORDERLYWEB_DOCUMENT.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return OrderlywebDocument.ORDERLYWEB_DOCUMENT.PARENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return OrderlywebDocument.ORDERLYWEB_DOCUMENT.IS_FILE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return OrderlywebDocument.ORDERLYWEB_DOCUMENT.EXTERNAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getPath();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getShow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDisplayName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getParent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getIsFile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getExternal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderlywebDocumentRecord value1(String value) {
        setPath(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderlywebDocumentRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderlywebDocumentRecord value3(Integer value) {
        setShow(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderlywebDocumentRecord value4(String value) {
        setDisplayName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderlywebDocumentRecord value5(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderlywebDocumentRecord value6(String value) {
        setParent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderlywebDocumentRecord value7(Integer value) {
        setIsFile(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderlywebDocumentRecord value8(Integer value) {
        setExternal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderlywebDocumentRecord values(String value1, String value2, Integer value3, String value4, String value5, String value6, Integer value7, Integer value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderlywebDocumentRecord
     */
    public OrderlywebDocumentRecord() {
        super(OrderlywebDocument.ORDERLYWEB_DOCUMENT);
    }

    /**
     * Create a detached, initialised OrderlywebDocumentRecord
     */
    public OrderlywebDocumentRecord(String path, String name, Integer show, String displayName, String description, String parent, Integer isFile, Integer external) {
        super(OrderlywebDocument.ORDERLYWEB_DOCUMENT);

        set(0, path);
        set(1, name);
        set(2, show);
        set(3, displayName);
        set(4, description);
        set(5, parent);
        set(6, isFile);
        set(7, external);
    }
}
