/*
 * This file is generated by jOOQ.
 */
package org.vaccineimpact.orderlyweb.db.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.UpdatableRecordImpl;
import org.vaccineimpact.orderlyweb.db.tables.OrderlywebPermission;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderlywebPermissionRecord extends UpdatableRecordImpl<OrderlywebPermissionRecord> implements Record1<String> {

    private static final long serialVersionUID = -1054518136;

    /**
     * Setter for <code>orderlyweb_permission.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>orderlyweb_permission.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row1<String> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    @Override
    public Row1<String> valuesRow() {
        return (Row1) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return OrderlywebPermission.ORDERLYWEB_PERMISSION.ID;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public OrderlywebPermissionRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public OrderlywebPermissionRecord values(String value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderlywebPermissionRecord
     */
    public OrderlywebPermissionRecord() {
        super(OrderlywebPermission.ORDERLYWEB_PERMISSION);
    }

    /**
     * Create a detached, initialised OrderlywebPermissionRecord
     */
    public OrderlywebPermissionRecord(String id) {
        super(OrderlywebPermission.ORDERLYWEB_PERMISSION);

        set(0, id);
    }
}
