/*
 * This file is generated by jOOQ.
*/
package org.vaccineimpact.orderlyweb.db.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;
import org.vaccineimpact.orderlyweb.db.tables.OrderlywebReportVersion;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderlywebReportVersionRecord extends UpdatableRecordImpl<OrderlywebReportVersionRecord> implements Record2<String, Boolean> {

    private static final long serialVersionUID = 1383649578;

    /**
     * Setter for <code>orderlyweb_report_version.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>orderlyweb_report_version.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>orderlyweb_report_version.published</code>.
     */
    public void setPublished(Boolean value) {
        set(1, value);
    }

    /**
     * Getter for <code>orderlyweb_report_version.published</code>.
     */
    public Boolean getPublished() {
        return (Boolean) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, Boolean> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, Boolean> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return OrderlywebReportVersion.ORDERLYWEB_REPORT_VERSION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field2() {
        return OrderlywebReportVersion.ORDERLYWEB_REPORT_VERSION.PUBLISHED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value2() {
        return getPublished();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderlywebReportVersionRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderlywebReportVersionRecord value2(Boolean value) {
        setPublished(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderlywebReportVersionRecord values(String value1, Boolean value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderlywebReportVersionRecord
     */
    public OrderlywebReportVersionRecord() {
        super(OrderlywebReportVersion.ORDERLYWEB_REPORT_VERSION);
    }

    /**
     * Create a detached, initialised OrderlywebReportVersionRecord
     */
    public OrderlywebReportVersionRecord(String id, Boolean published) {
        super(OrderlywebReportVersion.ORDERLYWEB_REPORT_VERSION);

        set(0, id);
        set(1, published);
    }
}
