/*
 * This file is generated by jOOQ.
 */
package org.vaccineimpact.orderlyweb.db.tables.records;


import java.sql.Timestamp;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;
import org.vaccineimpact.orderlyweb.db.tables.OrderlywebReportRun;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderlywebReportRunRecord extends UpdatableRecordImpl<OrderlywebReportRunRecord> implements Record11<String, String, Timestamp, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = 1735865193;

    /**
     * Setter for <code>orderlyweb_report_run.key</code>.
     */
    public void setKey(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>orderlyweb_report_run.key</code>.
     */
    public String getKey() {
        return (String) get(0);
    }

    /**
     * Setter for <code>orderlyweb_report_run.email</code>.
     */
    public void setEmail(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>orderlyweb_report_run.email</code>.
     */
    public String getEmail() {
        return (String) get(1);
    }

    /**
     * Setter for <code>orderlyweb_report_run.date</code>.
     */
    public void setDate(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>orderlyweb_report_run.date</code>.
     */
    public Timestamp getDate() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>orderlyweb_report_run.report_name</code>.
     */
    public void setReportName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>orderlyweb_report_run.report_name</code>.
     */
    public String getReportName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>orderlyweb_report_run.instances</code>.
     */
    public void setInstances(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>orderlyweb_report_run.instances</code>.
     */
    public String getInstances() {
        return (String) get(4);
    }

    /**
     * Setter for <code>orderlyweb_report_run.params</code>.
     */
    public void setParams(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>orderlyweb_report_run.params</code>.
     */
    public String getParams() {
        return (String) get(5);
    }

    /**
     * Setter for <code>orderlyweb_report_run.git_branch</code>.
     */
    public void setGitBranch(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>orderlyweb_report_run.git_branch</code>.
     */
    public String getGitBranch() {
        return (String) get(6);
    }

    /**
     * Setter for <code>orderlyweb_report_run.git_commit</code>.
     */
    public void setGitCommit(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>orderlyweb_report_run.git_commit</code>.
     */
    public String getGitCommit() {
        return (String) get(7);
    }

    /**
     * Setter for <code>orderlyweb_report_run.status</code>.
     */
    public void setStatus(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>orderlyweb_report_run.status</code>.
     */
    public String getStatus() {
        return (String) get(8);
    }

    /**
     * Setter for <code>orderlyweb_report_run.logs</code>.
     */
    public void setLogs(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>orderlyweb_report_run.logs</code>.
     */
    public String getLogs() {
        return (String) get(9);
    }

    /**
     * Setter for <code>orderlyweb_report_run.report_id</code>.
     */
    public void setReportId(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>orderlyweb_report_run.report_id</code>.
     */
    public String getReportId() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<String, String, Timestamp, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<String, String, Timestamp, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return OrderlywebReportRun.ORDERLYWEB_REPORT_RUN.KEY;
    }

    @Override
    public Field<String> field2() {
        return OrderlywebReportRun.ORDERLYWEB_REPORT_RUN.EMAIL;
    }

    @Override
    public Field<Timestamp> field3() {
        return OrderlywebReportRun.ORDERLYWEB_REPORT_RUN.DATE;
    }

    @Override
    public Field<String> field4() {
        return OrderlywebReportRun.ORDERLYWEB_REPORT_RUN.REPORT_NAME;
    }

    @Override
    public Field<String> field5() {
        return OrderlywebReportRun.ORDERLYWEB_REPORT_RUN.INSTANCES;
    }

    @Override
    public Field<String> field6() {
        return OrderlywebReportRun.ORDERLYWEB_REPORT_RUN.PARAMS;
    }

    @Override
    public Field<String> field7() {
        return OrderlywebReportRun.ORDERLYWEB_REPORT_RUN.GIT_BRANCH;
    }

    @Override
    public Field<String> field8() {
        return OrderlywebReportRun.ORDERLYWEB_REPORT_RUN.GIT_COMMIT;
    }

    @Override
    public Field<String> field9() {
        return OrderlywebReportRun.ORDERLYWEB_REPORT_RUN.STATUS;
    }

    @Override
    public Field<String> field10() {
        return OrderlywebReportRun.ORDERLYWEB_REPORT_RUN.LOGS;
    }

    @Override
    public Field<String> field11() {
        return OrderlywebReportRun.ORDERLYWEB_REPORT_RUN.REPORT_ID;
    }

    @Override
    public String component1() {
        return getKey();
    }

    @Override
    public String component2() {
        return getEmail();
    }

    @Override
    public Timestamp component3() {
        return getDate();
    }

    @Override
    public String component4() {
        return getReportName();
    }

    @Override
    public String component5() {
        return getInstances();
    }

    @Override
    public String component6() {
        return getParams();
    }

    @Override
    public String component7() {
        return getGitBranch();
    }

    @Override
    public String component8() {
        return getGitCommit();
    }

    @Override
    public String component9() {
        return getStatus();
    }

    @Override
    public String component10() {
        return getLogs();
    }

    @Override
    public String component11() {
        return getReportId();
    }

    @Override
    public String value1() {
        return getKey();
    }

    @Override
    public String value2() {
        return getEmail();
    }

    @Override
    public Timestamp value3() {
        return getDate();
    }

    @Override
    public String value4() {
        return getReportName();
    }

    @Override
    public String value5() {
        return getInstances();
    }

    @Override
    public String value6() {
        return getParams();
    }

    @Override
    public String value7() {
        return getGitBranch();
    }

    @Override
    public String value8() {
        return getGitCommit();
    }

    @Override
    public String value9() {
        return getStatus();
    }

    @Override
    public String value10() {
        return getLogs();
    }

    @Override
    public String value11() {
        return getReportId();
    }

    @Override
    public OrderlywebReportRunRecord value1(String value) {
        setKey(value);
        return this;
    }

    @Override
    public OrderlywebReportRunRecord value2(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public OrderlywebReportRunRecord value3(Timestamp value) {
        setDate(value);
        return this;
    }

    @Override
    public OrderlywebReportRunRecord value4(String value) {
        setReportName(value);
        return this;
    }

    @Override
    public OrderlywebReportRunRecord value5(String value) {
        setInstances(value);
        return this;
    }

    @Override
    public OrderlywebReportRunRecord value6(String value) {
        setParams(value);
        return this;
    }

    @Override
    public OrderlywebReportRunRecord value7(String value) {
        setGitBranch(value);
        return this;
    }

    @Override
    public OrderlywebReportRunRecord value8(String value) {
        setGitCommit(value);
        return this;
    }

    @Override
    public OrderlywebReportRunRecord value9(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public OrderlywebReportRunRecord value10(String value) {
        setLogs(value);
        return this;
    }

    @Override
    public OrderlywebReportRunRecord value11(String value) {
        setReportId(value);
        return this;
    }

    @Override
    public OrderlywebReportRunRecord values(String value1, String value2, Timestamp value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderlywebReportRunRecord
     */
    public OrderlywebReportRunRecord() {
        super(OrderlywebReportRun.ORDERLYWEB_REPORT_RUN);
    }

    /**
     * Create a detached, initialised OrderlywebReportRunRecord
     */
    public OrderlywebReportRunRecord(String key, String email, Timestamp date, String reportName, String instances, String params, String gitBranch, String gitCommit, String status, String logs, String reportId) {
        super(OrderlywebReportRun.ORDERLYWEB_REPORT_RUN);

        set(0, key);
        set(1, email);
        set(2, date);
        set(3, reportName);
        set(4, instances);
        set(5, params);
        set(6, gitBranch);
        set(7, gitCommit);
        set(8, status);
        set(9, logs);
        set(10, reportId);
    }
}
