/*
 * This file is generated by jOOQ.
 */
package org.vaccineimpact.orderlyweb.db.tables.records;


import java.sql.Timestamp;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;
import org.vaccineimpact.orderlyweb.db.tables.OrderlywebWorkflowRunReports;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderlywebWorkflowRunReportsRecord extends UpdatableRecordImpl<OrderlywebWorkflowRunReportsRecord> implements Record10<Integer, String, String, String, String, String, String, Timestamp, String, Integer> {

    private static final long serialVersionUID = 906560662;

    /**
     * Setter for <code>orderlyweb_workflow_run_reports.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>orderlyweb_workflow_run_reports.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>orderlyweb_workflow_run_reports.workflow_key</code>.
     */
    public void setWorkflowKey(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>orderlyweb_workflow_run_reports.workflow_key</code>.
     */
    public String getWorkflowKey() {
        return (String) get(1);
    }

    /**
     * Setter for <code>orderlyweb_workflow_run_reports.key</code>.
     */
    public void setKey(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>orderlyweb_workflow_run_reports.key</code>.
     */
    public String getKey() {
        return (String) get(2);
    }

    /**
     * Setter for <code>orderlyweb_workflow_run_reports.report</code>.
     */
    public void setReport(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>orderlyweb_workflow_run_reports.report</code>.
     */
    public String getReport() {
        return (String) get(3);
    }

    /**
     * Setter for <code>orderlyweb_workflow_run_reports.params</code>.
     */
    public void setParams(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>orderlyweb_workflow_run_reports.params</code>.
     */
    public String getParams() {
        return (String) get(4);
    }

    /**
     * Setter for <code>orderlyweb_workflow_run_reports.logs</code>.
     */
    public void setLogs(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>orderlyweb_workflow_run_reports.logs</code>.
     */
    public String getLogs() {
        return (String) get(5);
    }

    /**
     * Setter for <code>orderlyweb_workflow_run_reports.status</code>.
     */
    public void setStatus(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>orderlyweb_workflow_run_reports.status</code>.
     */
    public String getStatus() {
        return (String) get(6);
    }

    /**
     * Setter for <code>orderlyweb_workflow_run_reports.date</code>.
     */
    public void setDate(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>orderlyweb_workflow_run_reports.date</code>.
     */
    public Timestamp getDate() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>orderlyweb_workflow_run_reports.report_version</code>.
     */
    public void setReportVersion(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>orderlyweb_workflow_run_reports.report_version</code>.
     */
    public String getReportVersion() {
        return (String) get(8);
    }

    /**
     * Setter for <code>orderlyweb_workflow_run_reports.execution_order</code>.
     */
    public void setExecutionOrder(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>orderlyweb_workflow_run_reports.execution_order</code>.
     */
    public Integer getExecutionOrder() {
        return (Integer) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, String, String, String, String, String, String, Timestamp, String, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Integer, String, String, String, String, String, String, Timestamp, String, Integer> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return OrderlywebWorkflowRunReports.ORDERLYWEB_WORKFLOW_RUN_REPORTS.ID;
    }

    @Override
    public Field<String> field2() {
        return OrderlywebWorkflowRunReports.ORDERLYWEB_WORKFLOW_RUN_REPORTS.WORKFLOW_KEY;
    }

    @Override
    public Field<String> field3() {
        return OrderlywebWorkflowRunReports.ORDERLYWEB_WORKFLOW_RUN_REPORTS.KEY;
    }

    @Override
    public Field<String> field4() {
        return OrderlywebWorkflowRunReports.ORDERLYWEB_WORKFLOW_RUN_REPORTS.REPORT;
    }

    @Override
    public Field<String> field5() {
        return OrderlywebWorkflowRunReports.ORDERLYWEB_WORKFLOW_RUN_REPORTS.PARAMS;
    }

    @Override
    public Field<String> field6() {
        return OrderlywebWorkflowRunReports.ORDERLYWEB_WORKFLOW_RUN_REPORTS.LOGS;
    }

    @Override
    public Field<String> field7() {
        return OrderlywebWorkflowRunReports.ORDERLYWEB_WORKFLOW_RUN_REPORTS.STATUS;
    }

    @Override
    public Field<Timestamp> field8() {
        return OrderlywebWorkflowRunReports.ORDERLYWEB_WORKFLOW_RUN_REPORTS.DATE;
    }

    @Override
    public Field<String> field9() {
        return OrderlywebWorkflowRunReports.ORDERLYWEB_WORKFLOW_RUN_REPORTS.REPORT_VERSION;
    }

    @Override
    public Field<Integer> field10() {
        return OrderlywebWorkflowRunReports.ORDERLYWEB_WORKFLOW_RUN_REPORTS.EXECUTION_ORDER;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getWorkflowKey();
    }

    @Override
    public String component3() {
        return getKey();
    }

    @Override
    public String component4() {
        return getReport();
    }

    @Override
    public String component5() {
        return getParams();
    }

    @Override
    public String component6() {
        return getLogs();
    }

    @Override
    public String component7() {
        return getStatus();
    }

    @Override
    public Timestamp component8() {
        return getDate();
    }

    @Override
    public String component9() {
        return getReportVersion();
    }

    @Override
    public Integer component10() {
        return getExecutionOrder();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getWorkflowKey();
    }

    @Override
    public String value3() {
        return getKey();
    }

    @Override
    public String value4() {
        return getReport();
    }

    @Override
    public String value5() {
        return getParams();
    }

    @Override
    public String value6() {
        return getLogs();
    }

    @Override
    public String value7() {
        return getStatus();
    }

    @Override
    public Timestamp value8() {
        return getDate();
    }

    @Override
    public String value9() {
        return getReportVersion();
    }

    @Override
    public Integer value10() {
        return getExecutionOrder();
    }

    @Override
    public OrderlywebWorkflowRunReportsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public OrderlywebWorkflowRunReportsRecord value2(String value) {
        setWorkflowKey(value);
        return this;
    }

    @Override
    public OrderlywebWorkflowRunReportsRecord value3(String value) {
        setKey(value);
        return this;
    }

    @Override
    public OrderlywebWorkflowRunReportsRecord value4(String value) {
        setReport(value);
        return this;
    }

    @Override
    public OrderlywebWorkflowRunReportsRecord value5(String value) {
        setParams(value);
        return this;
    }

    @Override
    public OrderlywebWorkflowRunReportsRecord value6(String value) {
        setLogs(value);
        return this;
    }

    @Override
    public OrderlywebWorkflowRunReportsRecord value7(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public OrderlywebWorkflowRunReportsRecord value8(Timestamp value) {
        setDate(value);
        return this;
    }

    @Override
    public OrderlywebWorkflowRunReportsRecord value9(String value) {
        setReportVersion(value);
        return this;
    }

    @Override
    public OrderlywebWorkflowRunReportsRecord value10(Integer value) {
        setExecutionOrder(value);
        return this;
    }

    @Override
    public OrderlywebWorkflowRunReportsRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, Timestamp value8, String value9, Integer value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderlywebWorkflowRunReportsRecord
     */
    public OrderlywebWorkflowRunReportsRecord() {
        super(OrderlywebWorkflowRunReports.ORDERLYWEB_WORKFLOW_RUN_REPORTS);
    }

    /**
     * Create a detached, initialised OrderlywebWorkflowRunReportsRecord
     */
    public OrderlywebWorkflowRunReportsRecord(Integer id, String workflowKey, String key, String report, String params, String logs, String status, Timestamp date, String reportVersion, Integer executionOrder) {
        super(OrderlywebWorkflowRunReports.ORDERLYWEB_WORKFLOW_RUN_REPORTS);

        set(0, id);
        set(1, workflowKey);
        set(2, key);
        set(3, report);
        set(4, params);
        set(5, logs);
        set(6, status);
        set(7, date);
        set(8, reportVersion);
        set(9, executionOrder);
    }
}
