/*
 * This file is generated by jOOQ.
 */
package org.vaccineimpact.orderlyweb.db.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;
import org.vaccineimpact.orderlyweb.db.tables.OrderlywebUserGroup;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderlywebUserGroupRecord extends UpdatableRecordImpl<OrderlywebUserGroupRecord> implements Record2<String, Boolean> {

    private static final long serialVersionUID = -1933776913;

    /**
     * Setter for <code>orderlyweb_user_group.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>orderlyweb_user_group.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>orderlyweb_user_group.readonly</code>.
     */
    public void setReadonly(Boolean value) {
        set(1, value);
    }

    /**
     * Getter for <code>orderlyweb_user_group.readonly</code>.
     */
    public Boolean getReadonly() {
        return (Boolean) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, Boolean> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, Boolean> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return OrderlywebUserGroup.ORDERLYWEB_USER_GROUP.ID;
    }

    @Override
    public Field<Boolean> field2() {
        return OrderlywebUserGroup.ORDERLYWEB_USER_GROUP.READONLY;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public Boolean component2() {
        return getReadonly();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public Boolean value2() {
        return getReadonly();
    }

    @Override
    public OrderlywebUserGroupRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public OrderlywebUserGroupRecord value2(Boolean value) {
        setReadonly(value);
        return this;
    }

    @Override
    public OrderlywebUserGroupRecord values(String value1, Boolean value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderlywebUserGroupRecord
     */
    public OrderlywebUserGroupRecord() {
        super(OrderlywebUserGroup.ORDERLYWEB_USER_GROUP);
    }

    /**
     * Create a detached, initialised OrderlywebUserGroupRecord
     */
    public OrderlywebUserGroupRecord(String id, Boolean readonly) {
        super(OrderlywebUserGroup.ORDERLYWEB_USER_GROUP);

        set(0, id);
        set(1, readonly);
    }
}
