/*
 * This file is generated by jOOQ.
 */
package org.vaccineimpact.orderlyweb.db.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;
import org.vaccineimpact.orderlyweb.db.tables.ReportVersionWorkflow;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReportVersionWorkflowRecord extends UpdatableRecordImpl<ReportVersionWorkflowRecord> implements Record2<String, String> {

    private static final long serialVersionUID = 1429534189;

    /**
     * Setter for <code>report_version_workflow.report_version</code>.
     */
    public void setReportVersion(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>report_version_workflow.report_version</code>.
     */
    public String getReportVersion() {
        return (String) get(0);
    }

    /**
     * Setter for <code>report_version_workflow.workflow_id</code>.
     */
    public void setWorkflowId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>report_version_workflow.workflow_id</code>.
     */
    public String getWorkflowId() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return ReportVersionWorkflow.REPORT_VERSION_WORKFLOW.REPORT_VERSION;
    }

    @Override
    public Field<String> field2() {
        return ReportVersionWorkflow.REPORT_VERSION_WORKFLOW.WORKFLOW_ID;
    }

    @Override
    public String component1() {
        return getReportVersion();
    }

    @Override
    public String component2() {
        return getWorkflowId();
    }

    @Override
    public String value1() {
        return getReportVersion();
    }

    @Override
    public String value2() {
        return getWorkflowId();
    }

    @Override
    public ReportVersionWorkflowRecord value1(String value) {
        setReportVersion(value);
        return this;
    }

    @Override
    public ReportVersionWorkflowRecord value2(String value) {
        setWorkflowId(value);
        return this;
    }

    @Override
    public ReportVersionWorkflowRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReportVersionWorkflowRecord
     */
    public ReportVersionWorkflowRecord() {
        super(ReportVersionWorkflow.REPORT_VERSION_WORKFLOW);
    }

    /**
     * Create a detached, initialised ReportVersionWorkflowRecord
     */
    public ReportVersionWorkflowRecord(String reportVersion, String workflowId) {
        super(ReportVersionWorkflow.REPORT_VERSION_WORKFLOW);

        set(0, reportVersion);
        set(1, workflowId);
    }
}
