/*
 * This file is generated by jOOQ.
 */
package org.vaccineimpact.orderlyweb.db.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.vaccineimpact.orderlyweb.db.tables.ReportVersionView;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReportVersionViewRecord extends UpdatableRecordImpl<ReportVersionViewRecord> implements Record5<Integer, String, String, String, String> {

    private static final long serialVersionUID = 1579379135;

    /**
     * Setter for <code>report_version_view.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>report_version_view.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>report_version_view.report_version</code>.
     */
    public void setReportVersion(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>report_version_view.report_version</code>.
     */
    public String getReportVersion() {
        return (String) get(1);
    }

    /**
     * Setter for <code>report_version_view.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>report_version_view.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>report_version_view.database</code>.
     */
    public void setDatabase(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>report_version_view.database</code>.
     */
    public String getDatabase() {
        return (String) get(3);
    }

    /**
     * Setter for <code>report_version_view.query</code>.
     */
    public void setQuery(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>report_version_view.query</code>.
     */
    public String getQuery() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, String, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ReportVersionView.REPORT_VERSION_VIEW.ID;
    }

    @Override
    public Field<String> field2() {
        return ReportVersionView.REPORT_VERSION_VIEW.REPORT_VERSION;
    }

    @Override
    public Field<String> field3() {
        return ReportVersionView.REPORT_VERSION_VIEW.NAME;
    }

    @Override
    public Field<String> field4() {
        return ReportVersionView.REPORT_VERSION_VIEW.DATABASE;
    }

    @Override
    public Field<String> field5() {
        return ReportVersionView.REPORT_VERSION_VIEW.QUERY;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getReportVersion();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getDatabase();
    }

    @Override
    public String component5() {
        return getQuery();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getReportVersion();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getDatabase();
    }

    @Override
    public String value5() {
        return getQuery();
    }

    @Override
    public ReportVersionViewRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ReportVersionViewRecord value2(String value) {
        setReportVersion(value);
        return this;
    }

    @Override
    public ReportVersionViewRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public ReportVersionViewRecord value4(String value) {
        setDatabase(value);
        return this;
    }

    @Override
    public ReportVersionViewRecord value5(String value) {
        setQuery(value);
        return this;
    }

    @Override
    public ReportVersionViewRecord values(Integer value1, String value2, String value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReportVersionViewRecord
     */
    public ReportVersionViewRecord() {
        super(ReportVersionView.REPORT_VERSION_VIEW);
    }

    /**
     * Create a detached, initialised ReportVersionViewRecord
     */
    public ReportVersionViewRecord(Integer id, String reportVersion, String name, String database, String query) {
        super(ReportVersionView.REPORT_VERSION_VIEW);

        set(0, id);
        set(1, reportVersion);
        set(2, name);
        set(3, database);
        set(4, query);
    }
}
