/*
 * This file is generated by jOOQ.
 */
package org.vaccineimpact.orderlyweb.db.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.vaccineimpact.orderlyweb.db.tables.ReportVersionTag;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReportVersionTagRecord extends UpdatableRecordImpl<ReportVersionTagRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = -179892304;

    /**
     * Setter for <code>report_version_tag.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>report_version_tag.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>report_version_tag.report_version</code>.
     */
    public void setReportVersion(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>report_version_tag.report_version</code>.
     */
    public String getReportVersion() {
        return (String) get(1);
    }

    /**
     * Setter for <code>report_version_tag.tag</code>.
     */
    public void setTag(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>report_version_tag.tag</code>.
     */
    public String getTag() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ReportVersionTag.REPORT_VERSION_TAG.ID;
    }

    @Override
    public Field<String> field2() {
        return ReportVersionTag.REPORT_VERSION_TAG.REPORT_VERSION;
    }

    @Override
    public Field<String> field3() {
        return ReportVersionTag.REPORT_VERSION_TAG.TAG;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getReportVersion();
    }

    @Override
    public String component3() {
        return getTag();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getReportVersion();
    }

    @Override
    public String value3() {
        return getTag();
    }

    @Override
    public ReportVersionTagRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ReportVersionTagRecord value2(String value) {
        setReportVersion(value);
        return this;
    }

    @Override
    public ReportVersionTagRecord value3(String value) {
        setTag(value);
        return this;
    }

    @Override
    public ReportVersionTagRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReportVersionTagRecord
     */
    public ReportVersionTagRecord() {
        super(ReportVersionTag.REPORT_VERSION_TAG);
    }

    /**
     * Create a detached, initialised ReportVersionTagRecord
     */
    public ReportVersionTagRecord(Integer id, String reportVersion, String tag) {
        super(ReportVersionTag.REPORT_VERSION_TAG);

        set(0, id);
        set(1, reportVersion);
        set(2, tag);
    }
}
