#!/usr/bin/env bash
set -ex

if [ -n "${BUILDKITE-}" ]; then
    GIT_ID=${BUILDKITE_COMMIT:0:7}
else
    GIT_ID=$(git rev-parse --short=7 HEAD)
fi

if [ -n "${BUILDKITE-}" ]; then
    GIT_BRANCH=$BUILDKITE_BRANCH
else
    GIT_BRANCH=$(git symbolic-ref --short HEAD)
fi

# Deal with dependabot tags which look like
#
#   dependabot/npm_and_yarn/app/lodash-4.17.19
#
# But docker does not like
GIT_BRANCH=$(echo $GIT_BRANCH | sed 's;/;-;g')

BUILDKITE_DOCKER_AUTH_PATH=/var/lib/buildkite-agent/.docker/config.json

# Export env vars needed for running test dependencies
export ORG=vimc
export MONTAGU_ORDERLY_SERVER_VERSION=$(<$here/../config/orderly_server_version)
export GIT_ID=$GIT_ID
export GIT_BRANCH=$GIT_BRANCH
export ORDERLY_SERVER_USER_ID=$UID
export ORDERLY_DEMO_PATH=$here/../src/app/demo
export ORDERLY_DEMO=$(realpath $ORDERLY_DEMO_PATH)
