<?xml version="1.0" ?>
<SmellBaseline>
  <ManuallySuppressedIssues></ManuallySuppressedIssues>
  <CurrentIssues>
    <ID>CommentSpacing:org.vaccineimpact.orderlyweb.test_helpers.insertHelpers.kt:306</ID>
    <ID>CommentSpacing:org.vaccineimpact.orderlyweb.test_helpers.insertHelpers.kt:350</ID>
    <ID>Filename:org.vaccineimpact.orderlyweb.test_helpers.DatabaseTest.kt:1</ID>
    <ID>Filename:org.vaccineimpact.orderlyweb.test_helpers.RequestHelpers.kt:1</ID>
    <ID>FinalNewline:org.vaccineimpact.orderlyweb.test_helpers.CleanDatabaseTests.kt:1</ID>
    <ID>FinalNewline:org.vaccineimpact.orderlyweb.test_helpers.DatabaseTest.kt:1</ID>
    <ID>FinalNewline:org.vaccineimpact.orderlyweb.test_helpers.RequestHelpers.kt:1</ID>
    <ID>FunctionParameterNaming:insertHelpers.kt$git_branch: String? = "branch"</ID>
    <ID>FunctionParameterNaming:insertHelpers.kt$git_commit: String? = "commit"</ID>
    <ID>MatchingDeclarationName:DatabaseTest.kt$DatabaseTests</ID>
    <ID>MatchingDeclarationName:RequestHelpers.kt$TestTokenHeader : Authorization</ID>
    <ID>MaxLineLength:HttpClient.kt$HttpClient$.</ID>
    <ID>MaxLineLength:insertHelpers.kt$insertReportAndVersion(name, version, published, date, display, elapsed, gitBranch, gitCommit, addOrderlyWebReportVersion)</ID>
    <ID>NewLineAtEndOfFile:CleanDatabaseTests.kt$org.vaccineimpact.orderlyweb.test_helpers.CleanDatabaseTests.kt</ID>
    <ID>NewLineAtEndOfFile:DatabaseTest.kt$org.vaccineimpact.orderlyweb.test_helpers.DatabaseTest.kt</ID>
    <ID>NewLineAtEndOfFile:RequestHelpers.kt$org.vaccineimpact.orderlyweb.test_helpers.RequestHelpers.kt</ID>
    <ID>NoBlankLineBeforeRbrace:org.vaccineimpact.orderlyweb.test_helpers.CleanDatabaseTests.kt:31</ID>
    <ID>NoBlankLineBeforeRbrace:org.vaccineimpact.orderlyweb.test_helpers.CleanDatabaseTests.kt:36</ID>
    <ID>NoBlankLineBeforeRbrace:org.vaccineimpact.orderlyweb.test_helpers.DatabaseTest.kt:33</ID>
    <ID>NoBlankLineBeforeRbrace:org.vaccineimpact.orderlyweb.test_helpers.DatabaseTest.kt:35</ID>
    <ID>NoBlankLineBeforeRbrace:org.vaccineimpact.orderlyweb.test_helpers.insertHelpers.kt:291</ID>
    <ID>NoBlankLineBeforeRbrace:org.vaccineimpact.orderlyweb.test_helpers.insertHelpers.kt:355</ID>
    <ID>NoBlankLineBeforeRbrace:org.vaccineimpact.orderlyweb.test_helpers.insertHelpers.kt:357</ID>
    <ID>NoBlankLineBeforeRbrace:org.vaccineimpact.orderlyweb.test_helpers.insertHelpers.kt:468</ID>
    <ID>NoConsecutiveBlankLines:org.vaccineimpact.orderlyweb.test_helpers.DatabaseTest.kt:36</ID>
    <ID>NoConsecutiveBlankLines:org.vaccineimpact.orderlyweb.test_helpers.insertHelpers.kt:339</ID>
    <ID>NoConsecutiveBlankLines:org.vaccineimpact.orderlyweb.test_helpers.insertHelpers.kt:72</ID>
    <ID>PackageName:org.vaccineimpact.orderlyweb.test_helpers.CleanDatabaseTests.kt:1</ID>
    <ID>PackageName:org.vaccineimpact.orderlyweb.test_helpers.DatabaseTest.kt:1</ID>
    <ID>PackageName:org.vaccineimpact.orderlyweb.test_helpers.JSONValidator.kt:1</ID>
    <ID>PackageName:org.vaccineimpact.orderlyweb.test_helpers.RequestHelpers.kt:1</ID>
    <ID>PackageName:org.vaccineimpact.orderlyweb.test_helpers.http.HttpClient.kt:1</ID>
    <ID>PackageName:org.vaccineimpact.orderlyweb.test_helpers.insertHelpers.kt:1</ID>
    <ID>PackageNaming:CleanDatabaseTests.kt$package org.vaccineimpact.orderlyweb.test_helpers</ID>
    <ID>PackageNaming:DatabaseTest.kt$package org.vaccineimpact.orderlyweb.test_helpers</ID>
    <ID>PackageNaming:HttpClient.kt$package org.vaccineimpact.orderlyweb.test_helpers.http</ID>
    <ID>PackageNaming:JSONValidator.kt$package org.vaccineimpact.orderlyweb.test_helpers</ID>
    <ID>PackageNaming:RequestHelpers.kt$package org.vaccineimpact.orderlyweb.test_helpers</ID>
    <ID>PackageNaming:insertHelpers.kt$package org.vaccineimpact.orderlyweb.test_helpers</ID>
    <ID>TooGenericExceptionThrown:JSONValidator.kt$JSONValidator$throw Exception("Failed to parse text as JSON.\nText was: $jsonAsString\n\n$e")</ID>
    <ID>UnnecessaryAbstractClass:DatabaseTest.kt$DatabaseTests</ID>
    <ID>UtilityClassWithPublicConstructor:DatabaseTest.kt$DatabaseTests</ID>
  </CurrentIssues>
</SmellBaseline>
