/*
 * This file is generated by jOOQ.
*/
package org.vaccineimpact.orderlyweb.db;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.vaccineimpact.orderlyweb.db.tables.ArtefactFormat;
import org.vaccineimpact.orderlyweb.db.tables.Changelog;
import org.vaccineimpact.orderlyweb.db.tables.ChangelogLabel;
import org.vaccineimpact.orderlyweb.db.tables.Data;
import org.vaccineimpact.orderlyweb.db.tables.Depends;
import org.vaccineimpact.orderlyweb.db.tables.File;
import org.vaccineimpact.orderlyweb.db.tables.FileArtefact;
import org.vaccineimpact.orderlyweb.db.tables.FileInput;
import org.vaccineimpact.orderlyweb.db.tables.FilePurpose;
import org.vaccineimpact.orderlyweb.db.tables.OrderlySchema;
import org.vaccineimpact.orderlyweb.db.tables.OrderlySchemaTables;
import org.vaccineimpact.orderlyweb.db.tables.Parameters;
import org.vaccineimpact.orderlyweb.db.tables.ParametersType;
import org.vaccineimpact.orderlyweb.db.tables.Report;
import org.vaccineimpact.orderlyweb.db.tables.ReportVersion;
import org.vaccineimpact.orderlyweb.db.tables.ReportVersionArtefact;
import org.vaccineimpact.orderlyweb.db.tables.ReportVersionData;
import org.vaccineimpact.orderlyweb.db.tables.ReportVersionPackage;
import org.vaccineimpact.orderlyweb.db.tables.ReportVersionView;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = -857464804;

    /**
     * The reference instance of <code></code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>artefact_format</code>.
     */
    public final ArtefactFormat ARTEFACT_FORMAT = org.vaccineimpact.orderlyweb.db.tables.ArtefactFormat.ARTEFACT_FORMAT;

    /**
     * The table <code>changelog</code>.
     */
    public final Changelog CHANGELOG = org.vaccineimpact.orderlyweb.db.tables.Changelog.CHANGELOG;

    /**
     * The table <code>changelog_label</code>.
     */
    public final ChangelogLabel CHANGELOG_LABEL = org.vaccineimpact.orderlyweb.db.tables.ChangelogLabel.CHANGELOG_LABEL;

    /**
     * The table <code>data</code>.
     */
    public final Data DATA = org.vaccineimpact.orderlyweb.db.tables.Data.DATA;

    /**
     * The table <code>depends</code>.
     */
    public final Depends DEPENDS = org.vaccineimpact.orderlyweb.db.tables.Depends.DEPENDS;

    /**
     * The table <code>file</code>.
     */
    public final File FILE = org.vaccineimpact.orderlyweb.db.tables.File.FILE;

    /**
     * The table <code>file_artefact</code>.
     */
    public final FileArtefact FILE_ARTEFACT = org.vaccineimpact.orderlyweb.db.tables.FileArtefact.FILE_ARTEFACT;

    /**
     * The table <code>file_input</code>.
     */
    public final FileInput FILE_INPUT = org.vaccineimpact.orderlyweb.db.tables.FileInput.FILE_INPUT;

    /**
     * The table <code>file_purpose</code>.
     */
    public final FilePurpose FILE_PURPOSE = org.vaccineimpact.orderlyweb.db.tables.FilePurpose.FILE_PURPOSE;

    /**
     * The table <code>orderly_schema</code>.
     */
    public final OrderlySchema ORDERLY_SCHEMA = org.vaccineimpact.orderlyweb.db.tables.OrderlySchema.ORDERLY_SCHEMA;

    /**
     * The table <code>orderly_schema_tables</code>.
     */
    public final OrderlySchemaTables ORDERLY_SCHEMA_TABLES = org.vaccineimpact.orderlyweb.db.tables.OrderlySchemaTables.ORDERLY_SCHEMA_TABLES;

    /**
     * The table <code>parameters</code>.
     */
    public final Parameters PARAMETERS = org.vaccineimpact.orderlyweb.db.tables.Parameters.PARAMETERS;

    /**
     * The table <code>parameters_type</code>.
     */
    public final ParametersType PARAMETERS_TYPE = org.vaccineimpact.orderlyweb.db.tables.ParametersType.PARAMETERS_TYPE;

    /**
     * The table <code>report</code>.
     */
    public final Report REPORT = org.vaccineimpact.orderlyweb.db.tables.Report.REPORT;

    /**
     * The table <code>report_version</code>.
     */
    public final ReportVersion REPORT_VERSION = org.vaccineimpact.orderlyweb.db.tables.ReportVersion.REPORT_VERSION;

    /**
     * The table <code>report_version_artefact</code>.
     */
    public final ReportVersionArtefact REPORT_VERSION_ARTEFACT = org.vaccineimpact.orderlyweb.db.tables.ReportVersionArtefact.REPORT_VERSION_ARTEFACT;

    /**
     * The table <code>report_version_data</code>.
     */
    public final ReportVersionData REPORT_VERSION_DATA = org.vaccineimpact.orderlyweb.db.tables.ReportVersionData.REPORT_VERSION_DATA;

    /**
     * The table <code>report_version_package</code>.
     */
    public final ReportVersionPackage REPORT_VERSION_PACKAGE = org.vaccineimpact.orderlyweb.db.tables.ReportVersionPackage.REPORT_VERSION_PACKAGE;

    /**
     * The table <code>report_version_view</code>.
     */
    public final ReportVersionView REPORT_VERSION_VIEW = org.vaccineimpact.orderlyweb.db.tables.ReportVersionView.REPORT_VERSION_VIEW;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            ArtefactFormat.ARTEFACT_FORMAT,
            Changelog.CHANGELOG,
            ChangelogLabel.CHANGELOG_LABEL,
            Data.DATA,
            Depends.DEPENDS,
            File.FILE,
            FileArtefact.FILE_ARTEFACT,
            FileInput.FILE_INPUT,
            FilePurpose.FILE_PURPOSE,
            OrderlySchema.ORDERLY_SCHEMA,
            OrderlySchemaTables.ORDERLY_SCHEMA_TABLES,
            Parameters.PARAMETERS,
            ParametersType.PARAMETERS_TYPE,
            Report.REPORT,
            ReportVersion.REPORT_VERSION,
            ReportVersionArtefact.REPORT_VERSION_ARTEFACT,
            ReportVersionData.REPORT_VERSION_DATA,
            ReportVersionPackage.REPORT_VERSION_PACKAGE,
            ReportVersionView.REPORT_VERSION_VIEW);
    }
}
