version: '2'
services:
  proxy:
    image: vimc/montagu-reverse-proxy-minimal:master
    ports:
    - 80:80
    depends_on:
    - api
    logging:
      driver: syslog
  orderly_server:
    image: vimc/orderly.server:${MONTAGU_ORDERLY_SERVER_VERSION}
    user: ${ORDERLY_SERVER_USER_ID}
    command: --workers=1 --backup-period=10 /orderly
    ports:
      - "8321:8321"
    volumes:
      - ${MONTAGU_ORDERLY_PATH}:/orderly
    environment:
      REDIS_URL: redis://redis
  api:
    image: vimc/montagu-api:master
    ports:
    - "8080:8080"
    depends_on:
    - db
  db:
    image: vimc/montagu-db:master
    ports:
    - "5432:5432"
  redis:
    image: redis
