GIT_ID=$(git rev-parse --short=7 HEAD)
GIT_BRANCH=$(git symbolic-ref --short HEAD)
REGISTRY=docker.montagu.dide.ic.ac.uk:5000
REGISTRY_PUBLIC=vimc
NAME=orderlyweb-migrate

TAG=$REGISTRY/$NAME
COMMIT_TAG=$REGISTRY/$NAME:$GIT_ID
BRANCH_TAG=$REGISTRY/$NAME:$GIT_BRANCH

COMMIT_TAG_PUBLIC=$REGISTRY_PUBLIC/$NAME:$GIT_ID
BRANCH_TAG_PUBLIC=$REGISTRY_PUBLIC/$NAME:$GIT_BRANCH
