/*
 * This file is generated by jOOQ.
*/
package org.vaccineimpact.reporting_api.db;


import javax.annotation.Generated;

import org.vaccineimpact.reporting_api.db.tables.Orderly;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>orderly</code>.
     */
    public static final Orderly ORDERLY = org.vaccineimpact.reporting_api.db.tables.Orderly.ORDERLY;
}
