/*
 * This file is generated by jOOQ.
 */
package org.vaccineimpact.orderlyweb.db.tables;


import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.vaccineimpact.orderlyweb.db.DefaultSchema;
import org.vaccineimpact.orderlyweb.db.Keys;
import org.vaccineimpact.orderlyweb.db.tables.records.FileInputGlobalRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FileInputGlobal extends TableImpl<FileInputGlobalRecord> {

    private static final long serialVersionUID = -689540829;

    /**
     * The reference instance of <code>file_input_global</code>
     */
    public static final FileInputGlobal FILE_INPUT_GLOBAL = new FileInputGlobal();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FileInputGlobalRecord> getRecordType() {
        return FileInputGlobalRecord.class;
    }

    /**
     * The column <code>file_input_global.id</code>.
     */
    public final TableField<FileInputGlobalRecord, Integer> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>file_input_global.file_input</code>.
     */
    public final TableField<FileInputGlobalRecord, Integer> FILE_INPUT = createField(DSL.name("file_input"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>file_input_global.filename</code>.
     */
    public final TableField<FileInputGlobalRecord, String> FILENAME = createField(DSL.name("filename"), org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * Create a <code>file_input_global</code> table reference
     */
    public FileInputGlobal() {
        this(DSL.name("file_input_global"), null);
    }

    /**
     * Create an aliased <code>file_input_global</code> table reference
     */
    public FileInputGlobal(String alias) {
        this(DSL.name(alias), FILE_INPUT_GLOBAL);
    }

    /**
     * Create an aliased <code>file_input_global</code> table reference
     */
    public FileInputGlobal(Name alias) {
        this(alias, FILE_INPUT_GLOBAL);
    }

    private FileInputGlobal(Name alias, Table<FileInputGlobalRecord> aliased) {
        this(alias, aliased, null);
    }

    private FileInputGlobal(Name alias, Table<FileInputGlobalRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> FileInputGlobal(Table<O> child, ForeignKey<O, FileInputGlobalRecord> key) {
        super(child, key, FILE_INPUT_GLOBAL);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<FileInputGlobalRecord> getPrimaryKey() {
        return Keys.PK_FILE_INPUT_GLOBAL;
    }

    @Override
    public List<UniqueKey<FileInputGlobalRecord>> getKeys() {
        return Arrays.<UniqueKey<FileInputGlobalRecord>>asList(Keys.PK_FILE_INPUT_GLOBAL);
    }

    @Override
    public List<ForeignKey<FileInputGlobalRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<FileInputGlobalRecord, ?>>asList(Keys.FK_FILE_INPUT_GLOBAL_FILE_INPUT_1);
    }

    public FileInput fileInput() {
        return new FileInput(this, Keys.FK_FILE_INPUT_GLOBAL_FILE_INPUT_1);
    }

    @Override
    public FileInputGlobal as(String alias) {
        return new FileInputGlobal(DSL.name(alias), this);
    }

    @Override
    public FileInputGlobal as(Name alias) {
        return new FileInputGlobal(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public FileInputGlobal rename(String name) {
        return new FileInputGlobal(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FileInputGlobal rename(Name name) {
        return new FileInputGlobal(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
