/*
 * This file is generated by jOOQ.
 */
package org.vaccineimpact.orderlyweb.db.tables;


import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row1;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.vaccineimpact.orderlyweb.db.DefaultSchema;
import org.vaccineimpact.orderlyweb.db.Keys;
import org.vaccineimpact.orderlyweb.db.tables.records.FilePurposeRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FilePurpose extends TableImpl<FilePurposeRecord> {

    private static final long serialVersionUID = -1060589397;

    /**
     * The reference instance of <code>file_purpose</code>
     */
    public static final FilePurpose FILE_PURPOSE = new FilePurpose();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FilePurposeRecord> getRecordType() {
        return FilePurposeRecord.class;
    }

    /**
     * The column <code>file_purpose.name</code>.
     */
    public final TableField<FilePurposeRecord, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>file_purpose</code> table reference
     */
    public FilePurpose() {
        this(DSL.name("file_purpose"), null);
    }

    /**
     * Create an aliased <code>file_purpose</code> table reference
     */
    public FilePurpose(String alias) {
        this(DSL.name(alias), FILE_PURPOSE);
    }

    /**
     * Create an aliased <code>file_purpose</code> table reference
     */
    public FilePurpose(Name alias) {
        this(alias, FILE_PURPOSE);
    }

    private FilePurpose(Name alias, Table<FilePurposeRecord> aliased) {
        this(alias, aliased, null);
    }

    private FilePurpose(Name alias, Table<FilePurposeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> FilePurpose(Table<O> child, ForeignKey<O, FilePurposeRecord> key) {
        super(child, key, FILE_PURPOSE);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<FilePurposeRecord> getPrimaryKey() {
        return Keys.PK_FILE_PURPOSE;
    }

    @Override
    public List<UniqueKey<FilePurposeRecord>> getKeys() {
        return Arrays.<UniqueKey<FilePurposeRecord>>asList(Keys.PK_FILE_PURPOSE);
    }

    @Override
    public FilePurpose as(String alias) {
        return new FilePurpose(DSL.name(alias), this);
    }

    @Override
    public FilePurpose as(Name alias) {
        return new FilePurpose(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public FilePurpose rename(String name) {
        return new FilePurpose(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FilePurpose rename(Name name) {
        return new FilePurpose(name, null);
    }

    // -------------------------------------------------------------------------
    // Row1 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row1<String> fieldsRow() {
        return (Row1) super.fieldsRow();
    }
}
