/*
 * This file is generated by jOOQ.
*/
package org.vaccineimpact.orderlyweb.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.vaccineimpact.orderlyweb.db.DefaultSchema;
import org.vaccineimpact.orderlyweb.db.Keys;
import org.vaccineimpact.orderlyweb.db.tables.records.FileInputGlobalRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FileInputGlobal extends TableImpl<FileInputGlobalRecord> {

    private static final long serialVersionUID = -407099153;

    /**
     * The reference instance of <code>file_input_global</code>
     */
    public static final FileInputGlobal FILE_INPUT_GLOBAL = new FileInputGlobal();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FileInputGlobalRecord> getRecordType() {
        return FileInputGlobalRecord.class;
    }

    /**
     * The column <code>file_input_global.id</code>.
     */
    public final TableField<FileInputGlobalRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>file_input_global.file_input</code>.
     */
    public final TableField<FileInputGlobalRecord, Integer> FILE_INPUT = createField("file_input", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>file_input_global.filename</code>.
     */
    public final TableField<FileInputGlobalRecord, String> FILENAME = createField("filename", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * Create a <code>file_input_global</code> table reference
     */
    public FileInputGlobal() {
        this("file_input_global", null);
    }

    /**
     * Create an aliased <code>file_input_global</code> table reference
     */
    public FileInputGlobal(String alias) {
        this(alias, FILE_INPUT_GLOBAL);
    }

    private FileInputGlobal(String alias, Table<FileInputGlobalRecord> aliased) {
        this(alias, aliased, null);
    }

    private FileInputGlobal(String alias, Table<FileInputGlobalRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<FileInputGlobalRecord> getPrimaryKey() {
        return Keys.PK_FILE_INPUT_GLOBAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<FileInputGlobalRecord>> getKeys() {
        return Arrays.<UniqueKey<FileInputGlobalRecord>>asList(Keys.PK_FILE_INPUT_GLOBAL);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<FileInputGlobalRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<FileInputGlobalRecord, ?>>asList(Keys.FK_FILE_INPUT_GLOBAL_FILE_INPUT_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FileInputGlobal as(String alias) {
        return new FileInputGlobal(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public FileInputGlobal rename(String name) {
        return new FileInputGlobal(name, null);
    }
}
