/*
 * This file is generated by jOOQ.
*/
package org.vaccineimpact.orderlyweb.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;
import org.vaccineimpact.orderlyweb.db.DefaultSchema;
import org.vaccineimpact.orderlyweb.db.Keys;
import org.vaccineimpact.orderlyweb.db.tables.records.OrderlywebUserGroupUserRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderlywebUserGroupUser extends TableImpl<OrderlywebUserGroupUserRecord> {

    private static final long serialVersionUID = -78558059;

    /**
     * The reference instance of <code>orderlyweb_user_group_user</code>
     */
    public static final OrderlywebUserGroupUser ORDERLYWEB_USER_GROUP_USER = new OrderlywebUserGroupUser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrderlywebUserGroupUserRecord> getRecordType() {
        return OrderlywebUserGroupUserRecord.class;
    }

    /**
     * The column <code>orderlyweb_user_group_user.email</code>.
     */
    public final TableField<OrderlywebUserGroupUserRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>orderlyweb_user_group_user.user_group</code>.
     */
    public final TableField<OrderlywebUserGroupUserRecord, String> USER_GROUP = createField("user_group", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * Create a <code>orderlyweb_user_group_user</code> table reference
     */
    public OrderlywebUserGroupUser() {
        this("orderlyweb_user_group_user", null);
    }

    /**
     * Create an aliased <code>orderlyweb_user_group_user</code> table reference
     */
    public OrderlywebUserGroupUser(String alias) {
        this(alias, ORDERLYWEB_USER_GROUP_USER);
    }

    private OrderlywebUserGroupUser(String alias, Table<OrderlywebUserGroupUserRecord> aliased) {
        this(alias, aliased, null);
    }

    private OrderlywebUserGroupUser(String alias, Table<OrderlywebUserGroupUserRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<OrderlywebUserGroupUserRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<OrderlywebUserGroupUserRecord, ?>>asList(Keys.FK_ORDERLYWEB_USER_GROUP_USER_ORDERLYWEB_USER_1, Keys.FK_ORDERLYWEB_USER_GROUP_USER_ORDERLYWEB_USER_GROUP_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderlywebUserGroupUser as(String alias) {
        return new OrderlywebUserGroupUser(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public OrderlywebUserGroupUser rename(String name) {
        return new OrderlywebUserGroupUser(name, null);
    }
}
