/*
 * This file is generated by jOOQ.
*/
package org.vaccineimpact.orderlyweb.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.vaccineimpact.orderlyweb.db.DefaultSchema;
import org.vaccineimpact.orderlyweb.db.Keys;
import org.vaccineimpact.orderlyweb.db.tables.records.OrderlywebReportVersionRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderlywebReportVersion extends TableImpl<OrderlywebReportVersionRecord> {

    private static final long serialVersionUID = -825925865;

    /**
     * The reference instance of <code>orderlyweb_report_version</code>
     */
    public static final OrderlywebReportVersion ORDERLYWEB_REPORT_VERSION = new OrderlywebReportVersion();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrderlywebReportVersionRecord> getRecordType() {
        return OrderlywebReportVersionRecord.class;
    }

    /**
     * The column <code>orderlyweb_report_version.id</code>.
     */
    public final TableField<OrderlywebReportVersionRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>orderlyweb_report_version.published</code>.
     */
    public final TableField<OrderlywebReportVersionRecord, Boolean> PUBLISHED = createField("published", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * Create a <code>orderlyweb_report_version</code> table reference
     */
    public OrderlywebReportVersion() {
        this("orderlyweb_report_version", null);
    }

    /**
     * Create an aliased <code>orderlyweb_report_version</code> table reference
     */
    public OrderlywebReportVersion(String alias) {
        this(alias, ORDERLYWEB_REPORT_VERSION);
    }

    private OrderlywebReportVersion(String alias, Table<OrderlywebReportVersionRecord> aliased) {
        this(alias, aliased, null);
    }

    private OrderlywebReportVersion(String alias, Table<OrderlywebReportVersionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<OrderlywebReportVersionRecord> getPrimaryKey() {
        return Keys.PK_ORDERLYWEB_REPORT_VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<OrderlywebReportVersionRecord>> getKeys() {
        return Arrays.<UniqueKey<OrderlywebReportVersionRecord>>asList(Keys.PK_ORDERLYWEB_REPORT_VERSION);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<OrderlywebReportVersionRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<OrderlywebReportVersionRecord, ?>>asList(Keys.FK_ORDERLYWEB_REPORT_VERSION_REPORT_VERSION_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderlywebReportVersion as(String alias) {
        return new OrderlywebReportVersion(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public OrderlywebReportVersion rename(String name) {
        return new OrderlywebReportVersion(name, null);
    }
}
