/*
 * This file is generated by jOOQ.
 */
package org.vaccineimpact.orderlyweb.db.tables;


import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row1;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.vaccineimpact.orderlyweb.db.DefaultSchema;
import org.vaccineimpact.orderlyweb.db.Keys;
import org.vaccineimpact.orderlyweb.db.tables.records.OrderlySchemaTablesRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderlySchemaTables extends TableImpl<OrderlySchemaTablesRecord> {

    private static final long serialVersionUID = -239362759;

    /**
     * The reference instance of <code>orderly_schema_tables</code>
     */
    public static final OrderlySchemaTables ORDERLY_SCHEMA_TABLES = new OrderlySchemaTables();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrderlySchemaTablesRecord> getRecordType() {
        return OrderlySchemaTablesRecord.class;
    }

    /**
     * The column <code>orderly_schema_tables.name</code>.
     */
    public final TableField<OrderlySchemaTablesRecord, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>orderly_schema_tables</code> table reference
     */
    public OrderlySchemaTables() {
        this(DSL.name("orderly_schema_tables"), null);
    }

    /**
     * Create an aliased <code>orderly_schema_tables</code> table reference
     */
    public OrderlySchemaTables(String alias) {
        this(DSL.name(alias), ORDERLY_SCHEMA_TABLES);
    }

    /**
     * Create an aliased <code>orderly_schema_tables</code> table reference
     */
    public OrderlySchemaTables(Name alias) {
        this(alias, ORDERLY_SCHEMA_TABLES);
    }

    private OrderlySchemaTables(Name alias, Table<OrderlySchemaTablesRecord> aliased) {
        this(alias, aliased, null);
    }

    private OrderlySchemaTables(Name alias, Table<OrderlySchemaTablesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> OrderlySchemaTables(Table<O> child, ForeignKey<O, OrderlySchemaTablesRecord> key) {
        super(child, key, ORDERLY_SCHEMA_TABLES);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<OrderlySchemaTablesRecord> getPrimaryKey() {
        return Keys.PK_ORDERLY_SCHEMA_TABLES;
    }

    @Override
    public List<UniqueKey<OrderlySchemaTablesRecord>> getKeys() {
        return Arrays.<UniqueKey<OrderlySchemaTablesRecord>>asList(Keys.PK_ORDERLY_SCHEMA_TABLES);
    }

    @Override
    public OrderlySchemaTables as(String alias) {
        return new OrderlySchemaTables(DSL.name(alias), this);
    }

    @Override
    public OrderlySchemaTables as(Name alias) {
        return new OrderlySchemaTables(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public OrderlySchemaTables rename(String name) {
        return new OrderlySchemaTables(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrderlySchemaTables rename(Name name) {
        return new OrderlySchemaTables(name, null);
    }

    // -------------------------------------------------------------------------
    // Row1 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row1<String> fieldsRow() {
        return (Row1) super.fieldsRow();
    }
}
