/*
 * This file is generated by jOOQ.
*/
package org.vaccineimpact.orderlyweb.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;
import org.vaccineimpact.orderlyweb.db.DefaultSchema;
import org.vaccineimpact.orderlyweb.db.Keys;
import org.vaccineimpact.orderlyweb.db.tables.records.OrderlywebUserGroupReportPermissionRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderlywebUserGroupReportPermission extends TableImpl<OrderlywebUserGroupReportPermissionRecord> {

    private static final long serialVersionUID = 130915125;

    /**
     * The reference instance of <code>orderlyweb_user_group_report_permission</code>
     */
    public static final OrderlywebUserGroupReportPermission ORDERLYWEB_USER_GROUP_REPORT_PERMISSION = new OrderlywebUserGroupReportPermission();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrderlywebUserGroupReportPermissionRecord> getRecordType() {
        return OrderlywebUserGroupReportPermissionRecord.class;
    }

    /**
     * The column <code>orderlyweb_user_group_report_permission.id</code>.
     */
    public final TableField<OrderlywebUserGroupReportPermissionRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>orderlyweb_user_group_report_permission.report</code>.
     */
    public final TableField<OrderlywebUserGroupReportPermissionRecord, String> REPORT = createField("report", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * Create a <code>orderlyweb_user_group_report_permission</code> table reference
     */
    public OrderlywebUserGroupReportPermission() {
        this("orderlyweb_user_group_report_permission", null);
    }

    /**
     * Create an aliased <code>orderlyweb_user_group_report_permission</code> table reference
     */
    public OrderlywebUserGroupReportPermission(String alias) {
        this(alias, ORDERLYWEB_USER_GROUP_REPORT_PERMISSION);
    }

    private OrderlywebUserGroupReportPermission(String alias, Table<OrderlywebUserGroupReportPermissionRecord> aliased) {
        this(alias, aliased, null);
    }

    private OrderlywebUserGroupReportPermission(String alias, Table<OrderlywebUserGroupReportPermissionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<OrderlywebUserGroupReportPermissionRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<OrderlywebUserGroupReportPermissionRecord, ?>>asList(Keys.FK_ORDERLYWEB_USER_GROUP_REPORT_PERMISSION_ORDERLYWEB_USER_GROUP_PERMISSION_1, Keys.FK_ORDERLYWEB_USER_GROUP_REPORT_PERMISSION_REPORT_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderlywebUserGroupReportPermission as(String alias) {
        return new OrderlywebUserGroupReportPermission(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public OrderlywebUserGroupReportPermission rename(String name) {
        return new OrderlywebUserGroupReportPermission(name, null);
    }
}
