/*
 * This file is generated by jOOQ.
*/
package org.vaccineimpact.orderlyweb.db.tables;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;
import org.vaccineimpact.orderlyweb.db.DefaultSchema;
import org.vaccineimpact.orderlyweb.db.tables.records.OrderlywebUserGroupPermissionAllRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderlywebUserGroupPermissionAll extends TableImpl<OrderlywebUserGroupPermissionAllRecord> {

    private static final long serialVersionUID = -1294072495;

    /**
     * The reference instance of <code>orderlyweb_user_group_permission_all</code>
     */
    public static final OrderlywebUserGroupPermissionAll ORDERLYWEB_USER_GROUP_PERMISSION_ALL = new OrderlywebUserGroupPermissionAll();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrderlywebUserGroupPermissionAllRecord> getRecordType() {
        return OrderlywebUserGroupPermissionAllRecord.class;
    }

    /**
     * The column <code>orderlyweb_user_group_permission_all.id</code>.
     */
    public final TableField<OrderlywebUserGroupPermissionAllRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>orderlyweb_user_group_permission_all.user_group</code>.
     */
    public final TableField<OrderlywebUserGroupPermissionAllRecord, String> USER_GROUP = createField("user_group", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>orderlyweb_user_group_permission_all.permission</code>.
     */
    public final TableField<OrderlywebUserGroupPermissionAllRecord, String> PERMISSION = createField("permission", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>orderlyweb_user_group_permission_all.scope_prefix</code>.
     */
    public final TableField<OrderlywebUserGroupPermissionAllRecord, Object> SCOPE_PREFIX = createField("scope_prefix", org.jooq.impl.DefaultDataType.getDefaultDataType(""), this, "");

    /**
     * The column <code>orderlyweb_user_group_permission_all.scope_id</code>.
     */
    public final TableField<OrderlywebUserGroupPermissionAllRecord, String> SCOPE_ID = createField("scope_id", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>orderlyweb_user_group_permission_all</code> table reference
     */
    public OrderlywebUserGroupPermissionAll() {
        this("orderlyweb_user_group_permission_all", null);
    }

    /**
     * Create an aliased <code>orderlyweb_user_group_permission_all</code> table reference
     */
    public OrderlywebUserGroupPermissionAll(String alias) {
        this(alias, ORDERLYWEB_USER_GROUP_PERMISSION_ALL);
    }

    private OrderlywebUserGroupPermissionAll(String alias, Table<OrderlywebUserGroupPermissionAllRecord> aliased) {
        this(alias, aliased, null);
    }

    private OrderlywebUserGroupPermissionAll(String alias, Table<OrderlywebUserGroupPermissionAllRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderlywebUserGroupPermissionAll as(String alias) {
        return new OrderlywebUserGroupPermissionAll(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public OrderlywebUserGroupPermissionAll rename(String name) {
        return new OrderlywebUserGroupPermissionAll(name, null);
    }
}
