/*
 * This file is generated by jOOQ.
 */
package org.vaccineimpact.orderlyweb.db.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.vaccineimpact.orderlyweb.db.DefaultSchema;
import org.vaccineimpact.orderlyweb.db.Keys;
import org.vaccineimpact.orderlyweb.db.tables.records.OrderlySchemaRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderlySchema extends TableImpl<OrderlySchemaRecord> {

    private static final long serialVersionUID = -818740328;

    /**
     * The reference instance of <code>orderly_schema</code>
     */
    public static final OrderlySchema ORDERLY_SCHEMA = new OrderlySchema();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrderlySchemaRecord> getRecordType() {
        return OrderlySchemaRecord.class;
    }

    /**
     * The column <code>orderly_schema.schema_version</code>.
     */
    public final TableField<OrderlySchemaRecord, String> SCHEMA_VERSION = createField(DSL.name("schema_version"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>orderly_schema.orderly_version</code>.
     */
    public final TableField<OrderlySchemaRecord, String> ORDERLY_VERSION = createField(DSL.name("orderly_version"), org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>orderly_schema.created</code>.
     */
    public final TableField<OrderlySchemaRecord, Timestamp> CREATED = createField(DSL.name("created"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * Create a <code>orderly_schema</code> table reference
     */
    public OrderlySchema() {
        this(DSL.name("orderly_schema"), null);
    }

    /**
     * Create an aliased <code>orderly_schema</code> table reference
     */
    public OrderlySchema(String alias) {
        this(DSL.name(alias), ORDERLY_SCHEMA);
    }

    /**
     * Create an aliased <code>orderly_schema</code> table reference
     */
    public OrderlySchema(Name alias) {
        this(alias, ORDERLY_SCHEMA);
    }

    private OrderlySchema(Name alias, Table<OrderlySchemaRecord> aliased) {
        this(alias, aliased, null);
    }

    private OrderlySchema(Name alias, Table<OrderlySchemaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> OrderlySchema(Table<O> child, ForeignKey<O, OrderlySchemaRecord> key) {
        super(child, key, ORDERLY_SCHEMA);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<OrderlySchemaRecord> getPrimaryKey() {
        return Keys.PK_ORDERLY_SCHEMA;
    }

    @Override
    public List<UniqueKey<OrderlySchemaRecord>> getKeys() {
        return Arrays.<UniqueKey<OrderlySchemaRecord>>asList(Keys.PK_ORDERLY_SCHEMA);
    }

    @Override
    public OrderlySchema as(String alias) {
        return new OrderlySchema(DSL.name(alias), this);
    }

    @Override
    public OrderlySchema as(Name alias) {
        return new OrderlySchema(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public OrderlySchema rename(String name) {
        return new OrderlySchema(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrderlySchema rename(Name name) {
        return new OrderlySchema(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, Timestamp> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
