/*
 * This file is generated by jOOQ.
*/
package org.vaccineimpact.orderlyweb.db.tables;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;
import org.vaccineimpact.orderlyweb.db.DefaultSchema;
import org.vaccineimpact.orderlyweb.db.tables.records.OrderlywebSettingsRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderlywebSettings extends TableImpl<OrderlywebSettingsRecord> {

    private static final long serialVersionUID = -1752848937;

    /**
     * The reference instance of <code>orderlyweb_settings</code>
     */
    public static final OrderlywebSettings ORDERLYWEB_SETTINGS = new OrderlywebSettings();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrderlywebSettingsRecord> getRecordType() {
        return OrderlywebSettingsRecord.class;
    }

    /**
     * The column <code>orderlyweb_settings.auth_allow_guest</code>.
     */
    public final TableField<OrderlywebSettingsRecord, Boolean> AUTH_ALLOW_GUEST = createField("auth_allow_guest", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * Create a <code>orderlyweb_settings</code> table reference
     */
    public OrderlywebSettings() {
        this("orderlyweb_settings", null);
    }

    /**
     * Create an aliased <code>orderlyweb_settings</code> table reference
     */
    public OrderlywebSettings(String alias) {
        this(alias, ORDERLYWEB_SETTINGS);
    }

    private OrderlywebSettings(String alias, Table<OrderlywebSettingsRecord> aliased) {
        this(alias, aliased, null);
    }

    private OrderlywebSettings(String alias, Table<OrderlywebSettingsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderlywebSettings as(String alias) {
        return new OrderlywebSettings(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public OrderlywebSettings rename(String name) {
        return new OrderlywebSettings(name, null);
    }
}
