/*
 * This file is generated by jOOQ.
*/
package org.vaccineimpact.orderlyweb.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;
import org.vaccineimpact.orderlyweb.db.DefaultSchema;
import org.vaccineimpact.orderlyweb.db.Keys;
import org.vaccineimpact.orderlyweb.db.tables.records.OrderlywebPinnedReportGlobalRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderlywebPinnedReportGlobal extends TableImpl<OrderlywebPinnedReportGlobalRecord> {

    private static final long serialVersionUID = -655790921;

    /**
     * The reference instance of <code>orderlyweb_pinned_report_global</code>
     */
    public static final OrderlywebPinnedReportGlobal ORDERLYWEB_PINNED_REPORT_GLOBAL = new OrderlywebPinnedReportGlobal();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrderlywebPinnedReportGlobalRecord> getRecordType() {
        return OrderlywebPinnedReportGlobalRecord.class;
    }

    /**
     * The column <code>orderlyweb_pinned_report_global.ordering</code>.
     */
    public final TableField<OrderlywebPinnedReportGlobalRecord, Integer> ORDERING = createField("ordering", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>orderlyweb_pinned_report_global.report</code>.
     */
    public final TableField<OrderlywebPinnedReportGlobalRecord, String> REPORT = createField("report", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * Create a <code>orderlyweb_pinned_report_global</code> table reference
     */
    public OrderlywebPinnedReportGlobal() {
        this("orderlyweb_pinned_report_global", null);
    }

    /**
     * Create an aliased <code>orderlyweb_pinned_report_global</code> table reference
     */
    public OrderlywebPinnedReportGlobal(String alias) {
        this(alias, ORDERLYWEB_PINNED_REPORT_GLOBAL);
    }

    private OrderlywebPinnedReportGlobal(String alias, Table<OrderlywebPinnedReportGlobalRecord> aliased) {
        this(alias, aliased, null);
    }

    private OrderlywebPinnedReportGlobal(String alias, Table<OrderlywebPinnedReportGlobalRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<OrderlywebPinnedReportGlobalRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<OrderlywebPinnedReportGlobalRecord, ?>>asList(Keys.FK_ORDERLYWEB_PINNED_REPORT_GLOBAL_REPORT_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderlywebPinnedReportGlobal as(String alias) {
        return new OrderlywebPinnedReportGlobal(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public OrderlywebPinnedReportGlobal rename(String name) {
        return new OrderlywebPinnedReportGlobal(name, null);
    }
}
