/*
 * This file is generated by jOOQ.
 */
package org.vaccineimpact.orderlyweb.db.tables;


import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.vaccineimpact.orderlyweb.db.DefaultSchema;
import org.vaccineimpact.orderlyweb.db.Keys;
import org.vaccineimpact.orderlyweb.db.tables.records.OrderlywebReportTagRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderlywebReportTag extends TableImpl<OrderlywebReportTagRecord> {

    private static final long serialVersionUID = -1169701473;

    /**
     * The reference instance of <code>orderlyweb_report_tag</code>
     */
    public static final OrderlywebReportTag ORDERLYWEB_REPORT_TAG = new OrderlywebReportTag();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrderlywebReportTagRecord> getRecordType() {
        return OrderlywebReportTagRecord.class;
    }

    /**
     * The column <code>orderlyweb_report_tag.report</code>.
     */
    public final TableField<OrderlywebReportTagRecord, String> REPORT = createField(DSL.name("report"), org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>orderlyweb_report_tag.tag</code>.
     */
    public final TableField<OrderlywebReportTagRecord, String> TAG = createField(DSL.name("tag"), org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * Create a <code>orderlyweb_report_tag</code> table reference
     */
    public OrderlywebReportTag() {
        this(DSL.name("orderlyweb_report_tag"), null);
    }

    /**
     * Create an aliased <code>orderlyweb_report_tag</code> table reference
     */
    public OrderlywebReportTag(String alias) {
        this(DSL.name(alias), ORDERLYWEB_REPORT_TAG);
    }

    /**
     * Create an aliased <code>orderlyweb_report_tag</code> table reference
     */
    public OrderlywebReportTag(Name alias) {
        this(alias, ORDERLYWEB_REPORT_TAG);
    }

    private OrderlywebReportTag(Name alias, Table<OrderlywebReportTagRecord> aliased) {
        this(alias, aliased, null);
    }

    private OrderlywebReportTag(Name alias, Table<OrderlywebReportTagRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> OrderlywebReportTag(Table<O> child, ForeignKey<O, OrderlywebReportTagRecord> key) {
        super(child, key, ORDERLYWEB_REPORT_TAG);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<OrderlywebReportTagRecord> getPrimaryKey() {
        return Keys.PK_ORDERLYWEB_REPORT_TAG;
    }

    @Override
    public List<UniqueKey<OrderlywebReportTagRecord>> getKeys() {
        return Arrays.<UniqueKey<OrderlywebReportTagRecord>>asList(Keys.PK_ORDERLYWEB_REPORT_TAG);
    }

    @Override
    public List<ForeignKey<OrderlywebReportTagRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<OrderlywebReportTagRecord, ?>>asList(Keys.FK_ORDERLYWEB_REPORT_TAG_REPORT_1);
    }

    public Report report() {
        return new Report(this, Keys.FK_ORDERLYWEB_REPORT_TAG_REPORT_1);
    }

    @Override
    public OrderlywebReportTag as(String alias) {
        return new OrderlywebReportTag(DSL.name(alias), this);
    }

    @Override
    public OrderlywebReportTag as(Name alias) {
        return new OrderlywebReportTag(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public OrderlywebReportTag rename(String name) {
        return new OrderlywebReportTag(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrderlywebReportTag rename(Name name) {
        return new OrderlywebReportTag(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
