/*
 * This file is generated by jOOQ.
*/
package org.vaccineimpact.orderlyweb.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.vaccineimpact.orderlyweb.db.DefaultSchema;
import org.vaccineimpact.orderlyweb.db.Keys;
import org.vaccineimpact.orderlyweb.db.tables.records.OrderlySchemaTablesRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderlySchemaTables extends TableImpl<OrderlySchemaTablesRecord> {

    private static final long serialVersionUID = -1264020611;

    /**
     * The reference instance of <code>orderly_schema_tables</code>
     */
    public static final OrderlySchemaTables ORDERLY_SCHEMA_TABLES = new OrderlySchemaTables();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrderlySchemaTablesRecord> getRecordType() {
        return OrderlySchemaTablesRecord.class;
    }

    /**
     * The column <code>orderly_schema_tables.name</code>.
     */
    public final TableField<OrderlySchemaTablesRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>orderly_schema_tables</code> table reference
     */
    public OrderlySchemaTables() {
        this("orderly_schema_tables", null);
    }

    /**
     * Create an aliased <code>orderly_schema_tables</code> table reference
     */
    public OrderlySchemaTables(String alias) {
        this(alias, ORDERLY_SCHEMA_TABLES);
    }

    private OrderlySchemaTables(String alias, Table<OrderlySchemaTablesRecord> aliased) {
        this(alias, aliased, null);
    }

    private OrderlySchemaTables(String alias, Table<OrderlySchemaTablesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<OrderlySchemaTablesRecord> getPrimaryKey() {
        return Keys.PK_ORDERLY_SCHEMA_TABLES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<OrderlySchemaTablesRecord>> getKeys() {
        return Arrays.<UniqueKey<OrderlySchemaTablesRecord>>asList(Keys.PK_ORDERLY_SCHEMA_TABLES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderlySchemaTables as(String alias) {
        return new OrderlySchemaTables(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public OrderlySchemaTables rename(String name) {
        return new OrderlySchemaTables(name, null);
    }
}
