/*
 * This file is generated by jOOQ.
*/
package org.vaccineimpact.orderlyweb.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.vaccineimpact.orderlyweb.db.DefaultSchema;
import org.vaccineimpact.orderlyweb.db.Keys;
import org.vaccineimpact.orderlyweb.db.tables.records.ParametersTypeRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ParametersType extends TableImpl<ParametersTypeRecord> {

    private static final long serialVersionUID = -284034854;

    /**
     * The reference instance of <code>parameters_type</code>
     */
    public static final ParametersType PARAMETERS_TYPE = new ParametersType();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ParametersTypeRecord> getRecordType() {
        return ParametersTypeRecord.class;
    }

    /**
     * The column <code>parameters_type.name</code>.
     */
    public final TableField<ParametersTypeRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>parameters_type</code> table reference
     */
    public ParametersType() {
        this("parameters_type", null);
    }

    /**
     * Create an aliased <code>parameters_type</code> table reference
     */
    public ParametersType(String alias) {
        this(alias, PARAMETERS_TYPE);
    }

    private ParametersType(String alias, Table<ParametersTypeRecord> aliased) {
        this(alias, aliased, null);
    }

    private ParametersType(String alias, Table<ParametersTypeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ParametersTypeRecord> getPrimaryKey() {
        return Keys.PK_PARAMETERS_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ParametersTypeRecord>> getKeys() {
        return Arrays.<UniqueKey<ParametersTypeRecord>>asList(Keys.PK_PARAMETERS_TYPE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParametersType as(String alias) {
        return new ParametersType(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ParametersType rename(String name) {
        return new ParametersType(name, null);
    }
}
