/*
 * This file is generated by jOOQ.
 */
package org.vaccineimpact.orderlyweb.db.tables;


import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.vaccineimpact.orderlyweb.db.DefaultSchema;
import org.vaccineimpact.orderlyweb.db.Keys;
import org.vaccineimpact.orderlyweb.db.tables.records.ReportVersionWorkflowRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReportVersionWorkflow extends TableImpl<ReportVersionWorkflowRecord> {

    private static final long serialVersionUID = -1479283518;

    /**
     * The reference instance of <code>report_version_workflow</code>
     */
    public static final ReportVersionWorkflow REPORT_VERSION_WORKFLOW = new ReportVersionWorkflow();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReportVersionWorkflowRecord> getRecordType() {
        return ReportVersionWorkflowRecord.class;
    }

    /**
     * The column <code>report_version_workflow.report_version</code>.
     */
    public final TableField<ReportVersionWorkflowRecord, String> REPORT_VERSION = createField(DSL.name("report_version"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>report_version_workflow.workflow_id</code>.
     */
    public final TableField<ReportVersionWorkflowRecord, String> WORKFLOW_ID = createField(DSL.name("workflow_id"), org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * Create a <code>report_version_workflow</code> table reference
     */
    public ReportVersionWorkflow() {
        this(DSL.name("report_version_workflow"), null);
    }

    /**
     * Create an aliased <code>report_version_workflow</code> table reference
     */
    public ReportVersionWorkflow(String alias) {
        this(DSL.name(alias), REPORT_VERSION_WORKFLOW);
    }

    /**
     * Create an aliased <code>report_version_workflow</code> table reference
     */
    public ReportVersionWorkflow(Name alias) {
        this(alias, REPORT_VERSION_WORKFLOW);
    }

    private ReportVersionWorkflow(Name alias, Table<ReportVersionWorkflowRecord> aliased) {
        this(alias, aliased, null);
    }

    private ReportVersionWorkflow(Name alias, Table<ReportVersionWorkflowRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> ReportVersionWorkflow(Table<O> child, ForeignKey<O, ReportVersionWorkflowRecord> key) {
        super(child, key, REPORT_VERSION_WORKFLOW);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<ReportVersionWorkflowRecord> getPrimaryKey() {
        return Keys.PK_REPORT_VERSION_WORKFLOW;
    }

    @Override
    public List<UniqueKey<ReportVersionWorkflowRecord>> getKeys() {
        return Arrays.<UniqueKey<ReportVersionWorkflowRecord>>asList(Keys.PK_REPORT_VERSION_WORKFLOW);
    }

    @Override
    public ReportVersionWorkflow as(String alias) {
        return new ReportVersionWorkflow(DSL.name(alias), this);
    }

    @Override
    public ReportVersionWorkflow as(Name alias) {
        return new ReportVersionWorkflow(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ReportVersionWorkflow rename(String name) {
        return new ReportVersionWorkflow(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReportVersionWorkflow rename(Name name) {
        return new ReportVersionWorkflow(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
