/*
 * This file is generated by jOOQ.
*/
package org.vaccineimpact.orderlyweb.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.vaccineimpact.orderlyweb.db.DefaultSchema;
import org.vaccineimpact.orderlyweb.db.Keys;
import org.vaccineimpact.orderlyweb.db.tables.records.ReportVersionDataRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReportVersionData extends TableImpl<ReportVersionDataRecord> {

    private static final long serialVersionUID = 1980737171;

    /**
     * The reference instance of <code>report_version_data</code>
     */
    public static final ReportVersionData REPORT_VERSION_DATA = new ReportVersionData();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReportVersionDataRecord> getRecordType() {
        return ReportVersionDataRecord.class;
    }

    /**
     * The column <code>report_version_data.id</code>.
     */
    public final TableField<ReportVersionDataRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>report_version_data.report_version</code>.
     */
    public final TableField<ReportVersionDataRecord, String> REPORT_VERSION = createField("report_version", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>report_version_data.name</code>.
     */
    public final TableField<ReportVersionDataRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>report_version_data.database</code>.
     */
    public final TableField<ReportVersionDataRecord, String> DATABASE = createField("database", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>report_version_data.query</code>.
     */
    public final TableField<ReportVersionDataRecord, String> QUERY = createField("query", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>report_version_data.hash</code>.
     */
    public final TableField<ReportVersionDataRecord, String> HASH = createField("hash", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * Create a <code>report_version_data</code> table reference
     */
    public ReportVersionData() {
        this("report_version_data", null);
    }

    /**
     * Create an aliased <code>report_version_data</code> table reference
     */
    public ReportVersionData(String alias) {
        this(alias, REPORT_VERSION_DATA);
    }

    private ReportVersionData(String alias, Table<ReportVersionDataRecord> aliased) {
        this(alias, aliased, null);
    }

    private ReportVersionData(String alias, Table<ReportVersionDataRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ReportVersionDataRecord> getPrimaryKey() {
        return Keys.PK_REPORT_VERSION_DATA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ReportVersionDataRecord>> getKeys() {
        return Arrays.<UniqueKey<ReportVersionDataRecord>>asList(Keys.PK_REPORT_VERSION_DATA);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ReportVersionDataRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ReportVersionDataRecord, ?>>asList(Keys.FK_REPORT_VERSION_DATA_REPORT_VERSION_1, Keys.FK_REPORT_VERSION_DATA_DATA_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReportVersionData as(String alias) {
        return new ReportVersionData(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ReportVersionData rename(String name) {
        return new ReportVersionData(name, null);
    }
}
