/*
 * This file is generated by jOOQ.
*/
package org.vaccineimpact.orderlyweb.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.vaccineimpact.orderlyweb.db.DefaultSchema;
import org.vaccineimpact.orderlyweb.db.Keys;
import org.vaccineimpact.orderlyweb.db.tables.records.ReportVersionWorkflowRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReportVersionWorkflow extends TableImpl<ReportVersionWorkflowRecord> {

    private static final long serialVersionUID = 251737454;

    /**
     * The reference instance of <code>report_version_workflow</code>
     */
    public static final ReportVersionWorkflow REPORT_VERSION_WORKFLOW = new ReportVersionWorkflow();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReportVersionWorkflowRecord> getRecordType() {
        return ReportVersionWorkflowRecord.class;
    }

    /**
     * The column <code>report_version_workflow.report_version</code>.
     */
    public final TableField<ReportVersionWorkflowRecord, String> REPORT_VERSION = createField("report_version", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>report_version_workflow.workflow_id</code>.
     */
    public final TableField<ReportVersionWorkflowRecord, String> WORKFLOW_ID = createField("workflow_id", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * Create a <code>report_version_workflow</code> table reference
     */
    public ReportVersionWorkflow() {
        this("report_version_workflow", null);
    }

    /**
     * Create an aliased <code>report_version_workflow</code> table reference
     */
    public ReportVersionWorkflow(String alias) {
        this(alias, REPORT_VERSION_WORKFLOW);
    }

    private ReportVersionWorkflow(String alias, Table<ReportVersionWorkflowRecord> aliased) {
        this(alias, aliased, null);
    }

    private ReportVersionWorkflow(String alias, Table<ReportVersionWorkflowRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ReportVersionWorkflowRecord> getPrimaryKey() {
        return Keys.PK_REPORT_VERSION_WORKFLOW;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ReportVersionWorkflowRecord>> getKeys() {
        return Arrays.<UniqueKey<ReportVersionWorkflowRecord>>asList(Keys.PK_REPORT_VERSION_WORKFLOW);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReportVersionWorkflow as(String alias) {
        return new ReportVersionWorkflow(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ReportVersionWorkflow rename(String name) {
        return new ReportVersionWorkflow(name, null);
    }
}
