/*
 * This file is generated by jOOQ.
*/
package org.vaccineimpact.orderlyweb.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.vaccineimpact.orderlyweb.db.DefaultSchema;
import org.vaccineimpact.orderlyweb.db.Keys;
import org.vaccineimpact.orderlyweb.db.tables.records.ReportVersionCustomFieldsRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReportVersionCustomFields extends TableImpl<ReportVersionCustomFieldsRecord> {

    private static final long serialVersionUID = 198615118;

    /**
     * The reference instance of <code>report_version_custom_fields</code>
     */
    public static final ReportVersionCustomFields REPORT_VERSION_CUSTOM_FIELDS = new ReportVersionCustomFields();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReportVersionCustomFieldsRecord> getRecordType() {
        return ReportVersionCustomFieldsRecord.class;
    }

    /**
     * The column <code>report_version_custom_fields.id</code>.
     */
    public final TableField<ReportVersionCustomFieldsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>report_version_custom_fields.report_version</code>.
     */
    public final TableField<ReportVersionCustomFieldsRecord, String> REPORT_VERSION = createField("report_version", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>report_version_custom_fields.key</code>.
     */
    public final TableField<ReportVersionCustomFieldsRecord, String> KEY = createField("key", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>report_version_custom_fields.value</code>.
     */
    public final TableField<ReportVersionCustomFieldsRecord, String> VALUE = createField("value", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * Create a <code>report_version_custom_fields</code> table reference
     */
    public ReportVersionCustomFields() {
        this("report_version_custom_fields", null);
    }

    /**
     * Create an aliased <code>report_version_custom_fields</code> table reference
     */
    public ReportVersionCustomFields(String alias) {
        this(alias, REPORT_VERSION_CUSTOM_FIELDS);
    }

    private ReportVersionCustomFields(String alias, Table<ReportVersionCustomFieldsRecord> aliased) {
        this(alias, aliased, null);
    }

    private ReportVersionCustomFields(String alias, Table<ReportVersionCustomFieldsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ReportVersionCustomFieldsRecord> getPrimaryKey() {
        return Keys.PK_REPORT_VERSION_CUSTOM_FIELDS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ReportVersionCustomFieldsRecord>> getKeys() {
        return Arrays.<UniqueKey<ReportVersionCustomFieldsRecord>>asList(Keys.PK_REPORT_VERSION_CUSTOM_FIELDS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ReportVersionCustomFieldsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ReportVersionCustomFieldsRecord, ?>>asList(Keys.FK_REPORT_VERSION_CUSTOM_FIELDS_REPORT_VERSION_1, Keys.FK_REPORT_VERSION_CUSTOM_FIELDS_CUSTOM_FIELDS_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReportVersionCustomFields as(String alias) {
        return new ReportVersionCustomFields(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ReportVersionCustomFields rename(String name) {
        return new ReportVersionCustomFields(name, null);
    }
}
