/*
 * This file is generated by jOOQ.
 */
package org.vaccineimpact.orderlyweb.db.tables;


import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.vaccineimpact.orderlyweb.db.DefaultSchema;
import org.vaccineimpact.orderlyweb.db.Keys;
import org.vaccineimpact.orderlyweb.db.tables.records.ReportVersionTagRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReportVersionTag extends TableImpl<ReportVersionTagRecord> {

    private static final long serialVersionUID = -1065117324;

    /**
     * The reference instance of <code>report_version_tag</code>
     */
    public static final ReportVersionTag REPORT_VERSION_TAG = new ReportVersionTag();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReportVersionTagRecord> getRecordType() {
        return ReportVersionTagRecord.class;
    }

    /**
     * The column <code>report_version_tag.id</code>.
     */
    public final TableField<ReportVersionTagRecord, Integer> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>report_version_tag.report_version</code>.
     */
    public final TableField<ReportVersionTagRecord, String> REPORT_VERSION = createField(DSL.name("report_version"), org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>report_version_tag.tag</code>.
     */
    public final TableField<ReportVersionTagRecord, String> TAG = createField(DSL.name("tag"), org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * Create a <code>report_version_tag</code> table reference
     */
    public ReportVersionTag() {
        this(DSL.name("report_version_tag"), null);
    }

    /**
     * Create an aliased <code>report_version_tag</code> table reference
     */
    public ReportVersionTag(String alias) {
        this(DSL.name(alias), REPORT_VERSION_TAG);
    }

    /**
     * Create an aliased <code>report_version_tag</code> table reference
     */
    public ReportVersionTag(Name alias) {
        this(alias, REPORT_VERSION_TAG);
    }

    private ReportVersionTag(Name alias, Table<ReportVersionTagRecord> aliased) {
        this(alias, aliased, null);
    }

    private ReportVersionTag(Name alias, Table<ReportVersionTagRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> ReportVersionTag(Table<O> child, ForeignKey<O, ReportVersionTagRecord> key) {
        super(child, key, REPORT_VERSION_TAG);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<ReportVersionTagRecord> getPrimaryKey() {
        return Keys.PK_REPORT_VERSION_TAG;
    }

    @Override
    public List<UniqueKey<ReportVersionTagRecord>> getKeys() {
        return Arrays.<UniqueKey<ReportVersionTagRecord>>asList(Keys.PK_REPORT_VERSION_TAG);
    }

    @Override
    public List<ForeignKey<ReportVersionTagRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ReportVersionTagRecord, ?>>asList(Keys.FK_REPORT_VERSION_TAG_REPORT_VERSION_1, Keys.FK_REPORT_VERSION_TAG_TAG_1);
    }

    public ReportVersion reportVersion() {
        return new ReportVersion(this, Keys.FK_REPORT_VERSION_TAG_REPORT_VERSION_1);
    }

    public Tag tag() {
        return new Tag(this, Keys.FK_REPORT_VERSION_TAG_TAG_1);
    }

    @Override
    public ReportVersionTag as(String alias) {
        return new ReportVersionTag(DSL.name(alias), this);
    }

    @Override
    public ReportVersionTag as(Name alias) {
        return new ReportVersionTag(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ReportVersionTag rename(String name) {
        return new ReportVersionTag(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReportVersionTag rename(Name name) {
        return new ReportVersionTag(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
