database:
  source:
    driver: RSQLite::SQLite
    args:
      dbname: source.sqlite

fields:
  requester:
    required: true
    type: character
  author:
    required: true
    type: character
  comment:
    required: false
    type: character

changelog:
  internal:
    public: false
  public:
    public: true

tags:
  - dataset
  - plot

global_resources:
  global

remote:
  main:
    driver: "orderly::orderly_remote_path"
    primary: false
    default_branch_only: false
    args:
      path: "/orderly"
